### ISSUE TITLE
Erro no Número Sequencial do Registro - Banco Sicredi

### ISSUE THREAD

**Issue by MatheusVCoelho97** [BoletoNet/BoletoNetCore#118]
Boa tarde senhores, estou homologando alguns boletos pra Sicredi e me deparei com um erro no número sequencial do registro, ele acaba não seguindo os números corretos de linhas (Campo 365 - 400).

Remessa enviada:

![image](https://user-images.githubusercontent.com/61600216/119029156-ac242580-b97e-11eb-8790-f71ba91ae99c.png)

Retorno da Sicredi:

![image](https://user-images.githubusercontent.com/61600216/119029255-c8c05d80-b97e-11eb-8078-5e148000491e.png)

Há algo que eu possa fazer pra contornar esse erro ou é algo interno? Agradeço desde já!

**Comment by carloscds** [comment]
@MatheusVCoelho97 Pode corrigir o erro e mandar um PR por favor ?

**Comment by marcosgerene** [comment]
@carloscds

Estou analisando o caso, mas não consigo entender o porque as linhas dos detalhes estão incrementando, corri o código da Sicredi e não achei o incremento que ocorre no detalhe.

**Comment by marcosgerene** [comment]
@carloscds 

Corrigido em: https://github.com/BoletoNet/BoletoNetCore/pull/119

Por favor, enviar o Nuget assim que possível, obrigado

**Comment by MatheusVCoelho97** [comment]
Bom dia, testado a correção, tudo ok, agradeço.
