### ISSUE TITLE
REMESSA CNAB400 SICREDI

### ISSUE THREAD

**Issue by jonatanfelipesiqueira** [BoletoNet/BoletoNetCore#133]
Ao tentar enviar uma remessa pro banco percebi um problema, quero ver com os senhores qual a solucao,

Na imagem a seguir tem a sequencia 000001, que sai fixa em todos os boletos, o banco pede para que seja em sequencia
![image](https://user-images.githubusercontent.com/43968142/127224380-909cb96d-1815-4ef6-b065-0a3add4d65f6.png)

conforme essa imagem...
![image](https://user-images.githubusercontent.com/43968142/127224428-ea4b2b99-4b1e-40f8-85c4-4c04f6a01ff5.png)

como voces estao usando isto ?

**Comment by jonatanfelipesiqueira** [comment]
correçao, é no detalhe remessa, mas o problema existe mesmo..

**Comment by carloscds** [comment]
@jonatanfelipesiqueira isto é um contador de linhas, mas a imagem e do header, entao o numero esta correto. No detalhe ele incrementa.

**Comment by jonatanfelipesiqueira** [comment]
Ok, atualizei meu fork e ja havia sido corrigido
