### ISSUE TITLE
Leitura de Retorno

### ISSUE THREAD

**Issue by jonatanfelipesiqueira** [BoletoNet/BoletoNetCore#134]
Algum exemplo de como ler o arquivo de retorno ? nao encontrei nos demos

**Comment by carloscds** [comment]
@jonatanfelipesiqueira Existem alguns testes no projeto do BoletoNet que podem te orientar:
https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net.Testes/BancoUniprimeTeste.cs

**Comment by jonatanfelipesiqueira** [comment]
Consegui , Valeu
