### ISSUE TITLE
Erro em servidor linux

### ISSUE THREAD

**Issue by jonatanfelipesiqueira** [BoletoNet/BoletoNetCore#139]
![image](https://user-images.githubusercontent.com/43968142/128890863-56fffbc3-61a6-4dd5-bf83-f3f176c8dd0f.png)

ja aconteceu isso com alguem ? na hora de gerar os boletos ? estou usando servidor linux, esta tudo pronto rodando no windows ai quando fui passar pro linux da esse problema

**Comment by carloscds** [comment]
@jonatanfelipesiqueira instala a libgdiplus no seu Linux.
