### ISSUE TITLE
BB - Dias de protesto

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/BoletoNetCore#141]
Senhores,

Recebi a seguinte mensagem do BB

![image](https://user-images.githubusercontent.com/15945003/129910089-e0fd4eef-7bff-4f21-8729-ed35f73478e5.png)

No código o campo é vazio sempre:

https://github.com/BoletoNet/BoletoNetCore/blob/b1753fb476e184eccf8030bc76df6545cf987932/BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB400.cs#L145

```
reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0392, 002, 0, string.Empty, ' ');
```

**Comment by marcosgerene** [comment]
Entretanto, olhado o manual mais afundo, tenho isso:

![image](https://user-images.githubusercontent.com/15945003/129910988-14272875-c12a-4bba-b022-23a3f3a7f82f.png)


Onde comando fica na posição 109 e 110: 

![image](https://user-images.githubusercontent.com/15945003/129911165-a516e1c4-2cf8-49ef-903f-a11ee071408d.png)

Voltando ao código tenho: 
https://github.com/BoletoNet/BoletoNetCore/blob/b1753fb476e184eccf8030bc76df6545cf987932/BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB400.cs#L92

```
reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0109, 002, 0, boleto.CodigoMovimentoRetorno, ' ');
```

**Comment by marcosgerene** [comment]
@carloscds 

Estudando um pouco o código, minha ideia inicial seria essa:

```
reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0392, 002, 0, boleto.CodigoProtesto == TipoCodigoProtesto.ProtestarDiasCorridos ? boleto.DiasProtesto.ToString("00") : string.Empty, ' ');
```

Aceito sugestões.

**Comment by marcosgerene** [comment]
Update: Alterei dessa forma para uso próprio e resolveu, mas naõ se é o mais adequado.

Estou aguardando sugestões, caso contrário abro o PR assim mesmo.

**Comment by carloscds** [comment]
@marcosgerene se for opcional a informacao nao vejo problemas, pq nem todo mundo usa instrucao de protesto.
