### ISSUE TITLE
Divergências ITAU CNAB 240

### ISSUE THREAD

**Issue by Ipojuca** [BoletoNet/BoletoNetCore#146]
Eu recebi a documentação do ITAU para **remessa** padrão CNAB 240 e tem algumas diferenças.
Como estava listado o ITAU carteira 109 como homologado fiquei intrigado.
Por exemplo: na classe está criando o Segmento A, porém a doc não fala em Segmento  A somente  P .

Alguém por acaso tem uma documentação diferente?

Vou ajustar conforme a Documentação que recebi!
[COBRANCA 240 BYTES - VERSAO 7 0 - JULHO 2015.pdf](https://github.com/BoletoNet/BoletoNetCore/files/7117801/COBRANCA.240.BYTES.-.VERSAO.7.0.-.JULHO.2015.pdf)

**Comment by carloscds** [comment]
@Ipojuca Esta é mais recente: https://download.itau.com.br/bankline/layout_cobranca_400bytes_cnab_itau.pdf

**Comment by Ipojuca** [comment]
@carloscds o interessante é que eu recebi do proprio pessoal de integração do Itaú o manual que postei antes, porém depois achei a versão de 2017 para o layout 240 no site deles.

**Comment by carloscds** [comment]
@Ipojuca Banco e muito complicado!
