### ISSUE TITLE
Download da remessa

### ISSUE THREAD

**Issue by jonatanfelipesiqueira** [BoletoNet/BoletoNetCore#148]
Pessoal implementei o codigo de gerar o nome dos arquivos e download da remessa manualmente, pois vi que nao tem essa parte no componente, porém estou com um problema com o sicredi , meu servidor é linux e quando envio o arquivo pro sicredi da um problema o seguinte, arquivo do tipo unix nao aceito pelo sicredi , se eu gero pelo meu pc windows tudo ok ! , alguém tem exemplo ai de como faz pra eu modificar isso aqui 

Depois do arquivo ja gerado no servidor pelo componente , eu faco o download dele para um memoryStream e chamo pelo front-end para ser realizado o download

![image](https://user-images.githubusercontent.com/43968142/133274580-6280e645-35ae-4338-a4c1-ad51d2711c48.png)

creio eu que o problema esta ai 

Front : 
![image](https://user-images.githubusercontent.com/43968142/133274653-0441d4ab-dc8f-4789-bc87-7ede903cd1f4.png)

**Comment by carloscds** [comment]
@jonatanfelipesiqueira OS bancos usam padrão ANSI normalmente, deve ter ficado algum caracter no seu arquivo. Abre no Notepad++ e muda o tipo para ANSI.

**Comment by jonatanfelipesiqueira** [comment]
O problema é que esta gerando um arquivo tipo Unix, 

![image](https://user-images.githubusercontent.com/43968142/133435919-64a6f822-2a9b-4545-8dc2-1fa943b6d4d0.png)

**Comment by jonatanfelipesiqueira** [comment]
procurei aqui onde é escrito no componente a quebra de linha, estava pensando em mudar forçado pra \r\n padrao windows, mas n encontrei o codigo

**Comment by jonatanfelipesiqueira** [comment]
Corrigido!! , fiz uma funcao no javascript para alterar o tipo do arquivo quando é realizado o download
