### ISSUE TITLE
Validação do banco Caixa

### ISSUE THREAD

**Issue by tandradeflorencio** [BoletoNet/BoletoNetCore#16]
Boa tarde!

Encontrei um bug enquanto validava minha implementação:

Classe: BancoCaixa
Método: FormataCedente
Linha 34: Cedente.Codigo = codigoCedente.Length <= 6 ? codigoCedente.PadLeft(6, '0') : throw BoletoNetCoreException.CodigoCedenteInvalido(codigoCedente, 9);

Na verdade a mensagem de validação acusa a necessidade de 9 dígitos sendo que, na verdade, são obrigatórios apenas 6.

Abraços.

![Erro validação caixa](https://user-images.githubusercontent.com/22988455/62070063-19961d80-b210-11e9-93d5-75c240405804.png)

**Comment by olavorn** [comment]
Realmente. 

O correto seria...

```  c#
Cedente.Codigo = codigoCedente.Length <= 6 ? codigoCedente.PadLeft(6, '0') : throw BoletoNetCoreException.CodigoCedenteInvalido(codigoCedente, 6)
```

?
