### ISSUE TITLE
Impressão de boleto registrado

### ISSUE THREAD

**Issue by pbiajoni** [BoletoNet/BoletoNetCore#178]
Amigos, boa tarde!
Como eu conseguiria imprimir um boleto onde o código de barras e linha digitavel foram alterados.

Exemplo: Eu gero o boleto, envio para o Santander para registro, o Santander me devolve um novo código de barras e linha digitava.

Eu gravo no banco essas novas informações, mas preciso imprimir o boleto usando esses novos códigos, tem como?

Obrigado!

**Comment by carloscds** [comment]
@pbiajoni Se você esta eviando os dados pq o banco mudaria ?

**Comment by pbiajoni** [comment]
Levando em conta a pergunta do @carloscds que faz todo sentido estou fechando a Issue
