### ISSUE TITLE
Testes no AppVeyour

### ISSUE THREAD

**Issue by olavorn** [BoletoNet/BoletoNetCore#18]
@carloscds , Não seria o caso de descomentar a linha no arquivo ./build.ps1

``` poweshell
<#dotnet test $solutionTest#> 
```

para possibilitar a contabilização dos testes?

**Comment by carloscds** [comment]
Pode remover o comentário.

**Comment by olavorn** [comment]
Tentei algumas coisas, mas nada funcionou para incluir o relatório de testes no appveyour :(

Não pesquisei a fundo, mas também acho que seria uma boa restringir a branch de build para o BoletoNet/BoletoNetCore/master , pois do jeito que está, creio que ele esteja buildando qualquer fork. 

https://www.appveyor.com/docs/branches/

**Comment by carloscds** [comment]
@olavorn O build acontece a cada commit na master, por exemplo via PR. Foi asim que programei.

**Comment by olavorn** [comment]
@carloscds , mas então pq quando eu fiz um push no meu fork ele gerou uma nova build?

**Comment by carloscds** [comment]
@olavorn Se você tiver o appvoyor configurado no seu fork ele fara, caso contrario nao.
