### ISSUE TITLE
[Sicoob][CNAB240] DescricaoMovimentoRetorno

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/BoletoNetCore#183]
Boa tarde,

Estou recebendo um retorno 11 no CNAB240 do Sicoob, o retorno deveria ser "Titulo em Carteira (Em Ser)", entretanto o retorno vem como "" (string vazia) para mim.

Manual: [layout-cnab-240.xls](https://github.com/BoletoNet/BoletoNetCore/files/8653664/layout-cnab-240.xls)

Segue códigos segundo manual.

Segmento T
---

```
Código de Movimento de Retorno
'02' = Entrada Confirmada
'03' = Entrada Rejeitada
'04' = Transferência de Carteira/Entrada
'05' = Transferência de Carteira/Baixa
'06' = Liquidação
'07' = Confirmação do Recebimento da Instrução de Desconto
'08' = Confirmação do Recebimento do Cancelamento do Desconto
'09' = Baixa
'11' = Títulos em Carteira (Em Ser)
'12' = Confirmação Recebimento Instrução de Abatimento
'13' = Confirmação Recebimento Instrução de Cancelamento Abatimento
'14' = Confirmação Recebimento Instrução Alteração de Vencimento
'15' = Franco de Pagamento
'17' = Liquidação Após Baixa ou Liquidação Título Não Registrado
'19' = Confirmação Recebimento Instrução de Protesto
'20' = Confirmação Recebimento Instrução de Sustação/Cancelamento de Protesto
'23' = Remessa a Cartório (Aponte em Cartório)
'24' = Retirada de Cartório e Manutenção em Carteira
'25' = Protestado e Baixado (Baixa por Ter Sido Protestado)
'26' = Instrução Rejeitada
'27' = Confirmação do Pedido de Alteração de Outros Dados
'28' = Débito de Tarifas/Custas
'29' = Ocorrências do Pagador
'30' = Alteração de Dados Rejeitada
'33' = Confirmação da Alteração dos Dados do Rateio de Crédito
'34' = Confirmação do Cancelamento dos Dados do Rateio de Crédito
'35' = Confirmação do Desagendamento do Débito Automático
'36' = Confirmação de envio de e-mail/SMS
'37' = Envio de e-mail/SMS rejeitado
'38' = Confirmação de alteração do Prazo Limite de Recebimento (a data deve ser
'39' = Confirmação de Dispensa de Prazo Limite de Recebimento
'40' = Confirmação da alteração do número do título dado pelo Beneficiário
'41' = Confirmação da alteração do número controle do Participante
'42' = Confirmação da alteração dos dados do Pagador
'43' = Confirmação da alteração dos dados do Pagadorr/Avalista
'44' = Título pago com cheque devolvido
'45' = Título pago com cheque compensado
'46' = Instrução para cancelar protesto confirmada
'47' = Instrução para protesto para fins falimentares confirmada
'48' = Confirmação de instrução de transferência de carteira/modalidade de cobrança
'49' = Alteração de contrato de cobrança
'50' = Título pago com cheque pendente de liquidação
'51' = Título DDA reconhecido pelo Pagador
'52' = Título DDA não reconhecido pelo Pagador
'53' = Título DDA recusado pela CIP
'54' = Confirmação da Instrução de Baixa de Título Negativado sem Protesto
'55' = Confirmação de Pedido de Dispensa de Multa
'56' = Confirmação do Pedido de Cobrança de Multa
'57' = Confirmação do Pedido de Alteração de Cobrança de Juros
'58' = Confirmação do Pedido de Alteração do Valor/Data de Desconto
'59' = Confirmação do Pedido de Alteração do Beneficiário do Título
'60' = Confirmação do Pedido de Dispensa de Juros de Mora
'85' = Confirmação de Desistência de Protesto
'86' = Confirmação de cancelamento do Protesto
```

Segmento U
---

```
"Código de Movimento de Retorno
'02' = Entrada Confirmada
'03' = Entrada Rejeitada
'04' = Transferência de Carteira/Entrada
'05' = Transferência de Carteira/Baixa
'06' = Liquidação
'07' = Confirmação do Recebimento da Instrução de Desconto
'08' = Confirmação do Recebimento do Cancelamento do Desconto
'09' = Baixa
'11' = Títulos em Carteira (Em Ser)
'12' = Confirmação Recebimento Instrução de Abatimento
'13' = Confirmação Recebimento Instrução de Cancelamento Abatimento
'14' = Confirmação Recebimento Instrução Alteração de Vencimento
'15' = Franco de Pagamento
'17' = Liquidação Após Baixa ou Liquidação Título Não Registrado
'19' = Confirmação Recebimento Instrução de Protesto
'20' = Confirmação Recebimento Instrução de Sustação/Cancelamento de Protesto
'23' = Remessa a Cartório (Aponte em Cartório)
'24' = Retirada de Cartório e Manutenção em Carteira
'25' = Protestado e Baixado (Baixa por Ter Sido Protestado)
'26' = Instrução Rejeitada
'27' = Confirmação do Pedido de Alteração de Outros Dados
'28' = Débito de Tarifas/Custas
'29' = Ocorrências do Pagador
'30' = Alteração de Dados Rejeitada
'33' = Confirmação da Alteração dos Dados do Rateio de Crédito
'34' = Confirmação do Cancelamento dos Dados do Rateio de Crédito
'35' = Confirmação do Desagendamento do Débito Automático
'36' = Confirmação de envio de e-mail/SMS
'37' = Envio de e-mail/SMS rejeitado
'38' = Confirmação de alteração do Prazo Limite de Recebimento (a data deve ser
'39' = Confirmação de Dispensa de Prazo Limite de Recebimento
'40' = Confirmação da alteração do número do título dado pelo beneficiário
'41' = Confirmação da alteração do número controle do Participante
'42' = Confirmação da alteração dos dados do Pagador
'43' = Confirmação da alteração dos dados do Sacador/Avalista
'44' = Título pago com cheque devolvido
'45' = Título pago com cheque compensado
'46' = Instrução para cancelar protesto confirmada
'47' = Instrução para protesto para fins falimentares confirmada
'48' = Confirmação de instrução de transferência de carteira/modalidade de cobrança
'49' = Alteração de contrato de cobrança
'50' = Título pago com cheque pendente de liquidação
'51' = Título DDA reconhecido pelo pagador
'52' = Título DDA não reconhecido pelo pagador
'53' = Título DDA recusado pela CIP
'54' = Confirmação da Instrução de Baixa de Título Negativado sem Protesto
'55' = Confirmação de Pedido de Dispensa de Multa
'56' = Confirmação do Pedido de Cobrança de Multa
'57' = Confirmação do Pedido de Alteração de Cobrança de Juros
'58' = Confirmação do Pedido de Alteração do Valor/Data de Desconto
'59' = Confirmação do Pedido de Alteração do Beneficiário do Título
'60' = Confirmação do Pedido de Dispensa de Juros de Mora
```

Retorno atual
---

![image](https://user-images.githubusercontent.com/15945003/167460884-ec901feb-d071-4a50-b153-d0828bbca904.png)

[]'s

**Comment by carloscds** [comment]
@marcosgerene No arquivo de retorno esta correto e o codigo esta lendo errado ?

**Comment by marcosgerene** [comment]
@carloscds 

O código está correto no arquivo e na leitura, somente a descrição está vazia.

Eu monto um report em cima do retorno para meu cliente, ontem ele me perguntou o que era o retorno 11, porque a descrição estava vazia, foi então que fiz o debug e abri a issue.

**Comment by carloscds** [comment]
@marcosgerene olhando o código nao tem a ocorrencia 11 descrita, poderia corrigir e enviar um PR ?

**Comment by marcosgerene** [comment]
@carloscds 

Usa-se uma unica classe para os retornos do CNAB240 e nela faltam diversos códigos citados acima. Entretanto existe um comentário no método de descrição:
> // Considerando o arquivo CNAB padrão 240, acredita-se que os códigos de retorno são os mesmos.
> // Neste caso, utilizar sempre essa classe, para evitar duplicar esse código em cada banco implementado.

https://github.com/BoletoNet/BoletoNetCore/blob/66d909ba6a8830549956b7a06700b4d5e72eb9cd/BoletoNetCore/Util/Cnab.cs#L12

Alterar essa classe alteraria o funcionamento para diversos bancos. Adicionalmente, existem outras funções na mesma classe que usam este número para definir outras informações de descrição, o que faz a situação ficar ainda mais delicada.

Devo, mesmo assim, incluir os novos códigos neste classe e enviar o PR?

**Comment by carloscds** [comment]
@marcosgerene Eu, particularmente, nso uso as descricoes nos meu projetos,m e realmente muda de um banco para outro. Sugiro deixar com oesta e cada deve trata na sua aplicacao. Pode ser ?

**Comment by marcosgerene** [comment]
@carloscds 

>@marcosgerene Eu, particularmente, nso uso as descricoes nos meu projetos,m e realmente muda de um banco para outro. Sugiro deixar com oesta e cada deve trata na sua aplicacao. Pode ser ?

Não vejo problema em tratar isso na minha aplicação, mas vou deixar uma ideia/sugestão:

Na minha visão, existe um erro conceitual aqui. Entendo que se o projeto não pode tratar de forma assertiva esta mensagem de retorno, o atributo deveria ser removido para evitar que o usuário (desenvolvedor que usa o projeto) receba a informação imprecisa ou até mesmo incorreta. Acredito que não ter a informação é melhor do que tê-la dessa forma.

Se manter este campo é de alguma forma primordial, então sugiro que classe Cnab deveria ser estendida pelos bancos e conforme a necessidade vamos ajustando eventuais diferenças ou códigos faltantes no "banco-a-banco".

**Comment by carloscds** [comment]
@marcosgerene Eu trato isto apenas pelo codigo e a descricao coloco no ERP normalmente, então tudo é uma questão de uso. Para corrigir teria que implementar para cada banco, pois existem pequenas variações entre eles.

**Comment by marcosgerene** [comment]
@carloscds 

>@marcosgerene Eu trato isto apenas pelo codigo e a descricao coloco no ERP normalmente, então tudo é uma questão de uso. Para corrigir teria que implementar para cada banco, pois existem pequenas variações entre eles.

Entendo seu ponto, mas no final das contas temos uma descrição imprecisa/incorreta, mantenho a ideia de que este atributo não deveria existir, uma vez que implementar ele exige uma camada que extrapola as atribuições do projeto.

Bom, como disse anteriormente, trata-se de uma sugestão. Estou fechando a issue uma vez que a solução de tratar na minha aplicação já foi dada.
