### ISSUE TITLE
Sicredi - NossoNumero x NossoNumeroDV

### ISSUE THREAD

**Issue by marcianobandeira** [BoletoNet/BoletoNetCore#185]
Boa tarde,

Eu ja vinha utilizando a emissão de boletos do banco do brasil e do sicredi há algum tempo e tudo funcionando perfeitamente.

Agora estou iniciando a utilização do Bradesco, mas notei que a propriedade NossoNumero da Classe Boleto não vem com o dígito verificador, assim como ocorre para o sicredi.

No metodo FormataNossoNumero da classe BancoSicrediCarteira1 ocorre a concatenação:

        public void FormataNossoNumero(Boleto boleto)
        {
            var DataDocumento = boleto.DataEmissao.ToString("yy");
            var nossoNumero = boleto.NossoNumero;

            boleto.NossoNumero = string.Format("{0}2{1}", DataDocumento, nossoNumero.PadLeft(5, '0'));

            boleto.NossoNumeroDV = Mod11(Sequencial(boleto)).ToString();

            ********************************* AQUI **************************************
            boleto.NossoNumero = string.Concat(boleto.NossoNumero, Mod11(Sequencial(boleto)));

            boleto.NossoNumeroFormatado = string.Format("{0}/{1}-{2}", boleto.NossoNumero.Substring(0, 2), boleto.NossoNumero.Substring(2, 6), boleto.NossoNumero.Substring(8));            
        }

Contudo, esse comportamento não segue o padrão das classes BancoItauCarteira109 e BancoBradescoCarteira09 por exemplo, onde não há essa concatenação.

@carloscds voce acha que seria interessante padronizar esse comportamento?

Não cheguei a olhar ainda a sequencia que o métodos são chamados, mas a depender, essa mudança poderia impactar no método: FormataCodigoBarraCampoLivre da classe do sicredi também, pois alí é usado a propriedade NossoNumero, só não tenho certeza se já estará preenchida com o digito ou não.

**Comment by Ipojuca** [comment]
Boa tarde estou com um probleminha neste método também. Somente com SICREDI
Caso vc carregue um boleto que já foi gerado para uma reimpressão tentar calcular o digito novamente, pelo menos aqui na minha estrutura está acontecendo isso.
Para sanar estou verificando se o "nossonumero" já tem 9 posições o que em teoria e so formato 
 
```C#
   public void FormataNossoNumero(Boleto boleto)
        {
            if (boleto.NossoNumero.Length != 9)
            {
                var DataDocumento = boleto.DataEmissao.ToString("yy");
                var nossoNumero = boleto.NossoNumero;

                boleto.NossoNumero = string.Format("{0}2{1}", DataDocumento, nossoNumero.PadLeft(5, '0'));

                boleto.NossoNumeroDV = Mod11(Sequencial(boleto)).ToString();
                boleto.NossoNumero = string.Concat(boleto.NossoNumero, Mod11(Sequencial(boleto)));
            }

            boleto.NossoNumeroFormatado = string.Format("{0}/{1}-{2}", boleto.NossoNumero.Substring(0, 2), boleto.NossoNumero.Substring(2, 6), boleto.NossoNumero.Substring(8));
        }
```

**Comment by carloscds** [comment]
@Ipojuca Você esta informando o nosso numero na reimpressao ?

**Comment by Ipojuca** [comment]
Na verdade eu carrego os dados do Banco de dados para o objeto Boleto quando o sistema de impressão tenta validar os dados o nosso numero que já estava concatenado ao digito acaba gerando um digito extra. (Não sei se me fiz entender)
Talvez a solução possa ser também o que o @marcianobandeira falou sobre padronizar sem o digito aí não o problema pelo qual eu passei e fica um comportamento padrão.

**Comment by carloscds** [comment]
Obrigado @marcianobandeira , @Ipojuca pode fazer a alteracao e mandar um PR.

**Comment by Ipojuca** [comment]
@carloscds vou fazer mais testes deixando o digito verificador de fora do processo para manter o padrão com outros bancos e te envio amanhã no PR.

**Comment by Ipojuca** [comment]
@carloscds  vou anexar um ZIP com as alterações, os testes Unitarios passaram exceto o Online pois não tenho chave da API
[Sicredi.zip](https://github.com/BoletoNet/BoletoNetCore/files/9093311/Sicredi.zip)
.

**Comment by Ipojuca** [comment]
Bom dia @carloscds ei vi que vc aceitou o último PR que fiz na sexta dia 15/07 porém o pacote no Nuget se mantem na versão 235 do dia 12/07

**Comment by carloscds** [comment]
@Ipojuca Sim, nao geramos pacote a cada PR no Nuget, somente no MyGet: https://www.myget.org/gallery/boletonetcorebuild
