### ISSUE TITLE
Erro ao obter boleto em pdf

### ISSUE THREAD

**Issue by pbiajoni** [BoletoNet/BoletoNetCore#186]
Boa noite meus amigos,
Alguém sabe como resolver esse problema?

O BoletoNetCore.PDF já está instalado e o Wkhtmltopdf.NetCore também.

System.TypeLoadException: Could not load type 'Wkhtmltopdf.NetCore.HtmlAsPdf' from assembly 'Wkhtmltopdf.NetCore, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null'.

Obrigado!!

**Comment by carloscds** [comment]
@pbiajoni Você instala separado.

**Comment by pbiajoni** [comment]
Obrigado!
