### ISSUE TITLE
Suporte a net40

### ISSUE THREAD

**Issue by olavorn** [BoletoNet/BoletoNetCore#2]
@carloscds Acho que essa versão já dá suporte a v40 (exceto pdf). Poderiamos atualizar a documentação acerca disso.

**Comment by carloscds** [comment]
@olavorn Se mudar para .Net Standard não terá mais suporte.

**Comment by olavorn** [comment]
Não @carloscds , tá multitarget :) Ele builda tanto pra netstandard2.0 quanto pra net40

**Comment by carloscds** [comment]
@olavorn Ok, desde que nada de CORE seja colocado no código, ok! Multitarget é bem diferente de compatibilidade entre os frameworks, vc esta apenas dizendo que este projeto pode ser compilado em diferentes versões, respeitando-se as diferenças.

**Comment by carloscds** [comment]
@olavorn Para manter tudo em um único multi target project, teríamos que colocar coisas do tipo:
```csharp
#if NETFULL
    public static int EncryptionKeySize = 16;  // set for compatibility with previous version
#else
    public static int EncryptionKeySize = 24;
#endif	
```

**Comment by olavorn** [comment]
Isso. No caso, eu defini uma variavel NET4_0 para se referir ao legado. 
Avaliei colocar o NET2_0 mas sem o linq ia ficar muito ruim.. aí resolvi deixar só NET4_0 mesmo. 

Na prática, no BoletoNetCore não tem nada que demande esse tipo de construção por hora. E acho muito difícil que necessite dada a natureza do projeto. Teria que ser uma killer feature pra que todo mundo concorde em subir esse arranjo, na minha visão.

**Comment by carloscds** [comment]
@olavorn Tem que informar isto projeto informando isto, se for esta abordagem. no readme.me deve ter uma seção "Como contribuir" e isto tem que estar bem explicado la, senão teremos problemas.

**Comment by olavorn** [comment]
Sugestão do Texto para o Como Contribuir:

## Como Contribuir

Este projeto está dividido em 3 partes: 

### BoletoNetCore (Projeto Principal)
Responsável por guardar toda a lógica de leitura de remessa e retorno de arquivos e regras e impressão do boleto em hipertexto. Por ser um projeto **multitarget**, todo o código será avaliado se puder rodar corretamente tanto em netstandard2 quanto em net40. 

### BoletoNetCore.Pdf
Responsável pelos serviços de  impessão em PDF. 

### BoletoNetCore.Testes
Validação e testes de toda a lógica dos boletos.

- Em linhas gerais, novas carteiras deverão passar por validações e apresentar comprovação de passe nos testes propostos, contendo validações conforme proposto acima.
- Procure comentar todo o código para facilitar o entendimento e motivação para outros colegas. Embora o código original não seja muito comentado, não é motivo para que se crie o hábito. 
- Se houver a necessidade de incluir novas imagens ou recursos para impressão, abra uma issue primeiro, ou apenas use as pastas convencionadas no projeto para receber esses tipos de arquivo. /Images e /BoletoBancario
- Nomenclaturas e termos devem estar alinhados aos padrões definidos no CNAB: [https://cmsportal.febraban.org.br/Arquivos/documentos/PDF/Layout%20padrao%20CNAB240%20%20V%2010%2005%20-%2005_11_18.pdf](url)

...

**Comment by carloscds** [comment]
@olavorn Parece ok.
