### ISSUE TITLE
Erro ao gerar html do boleto "MontaHtmlEmbedded" - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jovemdan** [BoletoNet/BoletoNetCore#206]
Olá devs! Estou utilizando a lib boletoNetCore para geração de arquivos de remessa e geração de boletos, porém no momento de gerar o html do boleto estou tendo um erro na linha que chamo o método MontaHtmlEmbedded().
**Erro**:  Object reference not set to an instance of an object.
**Versão do dotnet:**  .net 6
**Versão do Wkhtmltopdf :**  `<PackageReference Include="Wkhtmltopdf.NetCore" Version="1.1.3" />`
Observações: 
Estou utilizando o .net 6 porém estou utilizando as mesmas versões do Wkhtmltopdf que a própria lib BoletoNetCore usa, as versões mais recentes não consegui usar por ser um pouco diferente da versão implementada pela própria lib.

Objeto boleto que esta sendo preenchido
![image](https://user-images.githubusercontent.com/25301052/205200660-f4a3445a-c979-437d-8e88-0bc95a9baa0d.png)

Código de geração de boleto:

```
private void GerarPdfBoletos(Boletos boletos)
        {
            RotativaConfiguration.RotativaPath = "Rotativa";
            RotativaConfiguration.IsWindows = true;

            try
            {
                var html = new StringBuilder();
                foreach (var boletoTmp in boletos)
                {
                    var boletoParaImpressao = new BoletoBancario
                    {
                        Boleto = boletoTmp,
                        Banco = boletos.Banco,
                        OcultarInstrucoes = false,
                        MostrarComprovanteEntrega = false,
                        MostrarEnderecoBeneficiario = true,
                        ExibirDemonstrativo = true
                    };
                    html.Append("<div style=\"page-break-after: always;\">");

                    html.Append(boletoParaImpressao.MontaHtmlEmbedded()); //erro
                    html.Append("</div>");

                    var boletoHtml = html.ToString();
                    System.IO.File.WriteAllText("nomeArquivoHTML", boletoHtml);
                    var pdf = new Wkhtmltopdf.NetCore.HtmlAsPdf().GetPDF(boletoHtml);
                    using (var fs = new FileStream("nomeArquivoPDF", FileMode.Create))
                        fs.Write(pdf, 0, pdf.Length);
                }

            }
            catch (Exception ex)
            {

                throw;
            }
        }
```

Pasta rotativa: 
![image](https://user-images.githubusercontent.com/25301052/205200393-3db694d0-c9bd-4800-b674-6425ec009d01.png)

Evidências: 
![image](https://user-images.githubusercontent.com/25301052/205200323-044a2137-32e2-442d-9259-25d00f0fe894.png)

**Comment by carloscds** [comment]
@jovemdan Como sugestão, você pode usar este componente para gerar o PDF: https://www.nuget.org/packages/HtmlToPDFCore/

**Comment by jovemdan** [comment]
@carloscds  Obrigado pela indicação desse pacote, porém o erro que estou tendo é no método que monta o html, no caso **MontaHtmlEmbedded**, método no qual existe dentro da classe **BoletoBancario**  que faz parte da lib boletoNetcore, pode me auxiliar nessa questão?, existe algum outro componente só pra montar esse html?

**Comment by carloscds** [comment]
@jovemdan No seu print vc ta chamando a rotina do PDF, tentou chmar direto a do HTML ? Pois ela nao usa o Rotativa.
