### ISSUE TITLE
Erro ao Gerar HTML .net6 executando aplicação via docker

### ISSUE THREAD

**Issue by jeumichelin** [BoletoNet/BoletoNetCore#212]
Olá!
Gostaria de saber se alguém poderia me ajudar, estou com o seguinte problema para gerar o HTML do boleto:
Tentei adicionar ao meu dockerfile a sugestão da issue https://github.com/BoletoNet/BoletoNetCore/issues/25, mas não tive sucesso.

System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.\n ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.\n at System.Drawing.LibraryResolver.EnsureRegistered()\n at System.Drawing.SafeNativeMethods.Gdip..cctor()\n --- End of inner exception stack trace ---\n at System.Drawing.SafeNativeMethods.Gdip.get_ThreadData()\n at System.Drawing.Brushes.GetBrush(Object key, Color color)\n at BoletoNetCore.BoletoBancario.MontaHtmlEmbedded(Boolean convertLinhaDigitavelToImage, Boolean usaCsspdf, String urlImagemLogoBeneficiario, String pixString)\n ...

Muito obrigado!

**Obs**. Essa issue havia sido aberta no lugar errado. https://github.com/BoletoNet/boletonet/issues/958

**Comment by carloscds** [comment]
@jeumichelin veja se resolve: https://developers.de/2018/01/22/how-to-use-system-drawing-in-net-core/

**Comment by jeumichelin** [comment]
@carloscds, muito obrigado pelo seu empenho em me ajudar!!

Consegui resolver da seguinte forma:

- Adicionei o arquivo runtimeconfig.template.json no mesmo diretório do .csproj da API.

```json
{
  "configProperties": {
    "System.Drawing.EnableUnixSupport": true
  }
}
```

- Instalei o [HtmlToPDFCore](https://www.nuget.org/packages/HtmlToPDFCore#readme-body-tab) conforme a sua sugestão
```csharp
using BoletoNetCore;
using System;
using System.Text;
using Wkhtmltopdf.NetCore;
...
        public string GerarImpressaoBoletoPDF(BoletoProvisorio boleto)
        {
            try
            {
                var boletoBancario = BoletoBancarioMapper.Map(boleto);

                var boletoHtml = GerarHtml(boletoBancario);
                var htmlToPdf = new HtmlToPDFCore.HtmlToPDF();
                var boletoPDF = htmlToPdf.ReturnPDF(boletoHtml);
                var boletoBase64 = Convert.ToBase64String(boletoPDF);

                return boletoBase64;
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        private string GerarHtml(BoletoBancario boletoBancario)
        {
            const double TAMANHO_FONTES_TEXTO = 12;
            const double TAMANHO_FONTE_ROTULOS = 10;
            const double TAMANHO_FONTES_INSTRUCAO_IMPRESSAO = 14;
            const double TAMANHO_FONTES_INSTRUCOES = 14;

            var html = new StringBuilder();

            // Trecho com css para ajustar fontes
            html.AppendLine("<style>");
            html.AppendFormat(".cp$1 font-size: {0}px !important; $2", TAMANHO_FONTES_TEXTO);
            html.AppendFormat(".ctN$1 font-size: {0}px !important; $2", TAMANHO_FONTE_ROTULOS);
            html.AppendFormat(".cpN$1 font-size: {0}px !important; $2", TAMANHO_FONTES_TEXTO);
            html.AppendFormat(".ti$1 font-size: {0}px !important; $2", TAMANHO_FONTES_INSTRUCAO_IMPRESSAO);
            html.AppendFormat(".ct$1 font-size: {0}px !important; $2", TAMANHO_FONTE_ROTULOS);
            html.AppendFormat(".t$1 font-size: {0}px !important; $2", TAMANHO_FONTE_ROTULOS);
            html.AppendFormat(".it$1 font-size: {0}px !important; $2", TAMANHO_FONTES_INSTRUCOES);
            html.AppendLine("</style>");

            html.AppendLine("<div style=\"page-break-after: always;\">");
            html.AppendLine(boletoBancario.MontaHtmlEmbedded());
            html.AppendLine("</div>");

            var htmlEditado = html
                .ToString()
                .Replace("$1", "{")
                .Replace("$2", "}");

            return htmlEditado;
        }
```

- Adicionei ao Dockerfile as seguintes dependências
```yml
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*
WORKDIR /app
EXPOSE 80
EXPOSE 443
```
Dessa forma funcionou tanto executando no container quanto pelo windows.

Referência:

- https://learn.microsoft.com/pt-br/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only
