### ISSUE TITLE
BoletoNetCore.ArquivoRetorno não está funcionando com Itaú e Santander

### ISSUE THREAD

**Issue by renydev** [BoletoNet/BoletoNetCore#216]
Bom dia.

o BoletoNetCore.ArquivoRetorno não funciona para leitura de arquivos retornos de Itaú na carteira 109 e Santander na carteira 101.

Eu estou enviando um arquivo base64 para minha API e quando eu converto, passo para Stream e uso o new BoletoNetCore.ArquivoRetorno ele dá alguns erros.

Para o Santander: "Banco 33 não implementou os Ids do Registro Retorno do CNAB400"
mas não faz sentido, eu peguei o arquivo direto do banco.

Para o Itaú: "Object reference not set to an instance of an object"

Os dois eu estou usando CNAB400.

``` [HttpPost]
    [Route("retorno")]
    public async Task<ActionResult> PostAdicionarRetorno([FromBody] RetornoDto retorno)
    {
      BoletoNetCore.ArquivoRetorno arquivoRetorno;
      try
      {
        Stream str = new MemoryStream(Convert.FromBase64String(retorno.DocumentoCompleto));
        arquivoRetorno = new BoletoNetCore.ArquivoRetorno(str);
      }
      catch (Exception e)
      {

        throw;
      }

      return Ok(retornos);
    }```

**Comment by carloscds** [comment]
@renydev Você conseguiu resolver ?

**Comment by renydev** [comment]
Rapaz, não consegui, eu vou pegar novamente depois, eu não sei muito bem como debugar o projeto, eu não estou entendendo muito bem como usar a ferramenta... eu cheguei aqui pelo seu vídeo no Youtube mas eu preciso me debruçar mais sobre o projeto antes de mandar mais perguntas, me desculpe =D

**Comment by carloscds** [comment]
@renydev Da uma olhada nos projetos de testes, podem te ajudar.
