### ISSUE TITLE
Package Separado para o BoletoNetCore.Pdf

### ISSUE THREAD

**Issue by olavorn** [BoletoNet/BoletoNetCore#22]
Creio que um passo necessário seria disponibilizar no nuget o BoletoNetCore.Pdf na mesma linha do BoletoNetCore no nuget.

**Comment by olavorn** [comment]
Inclusive, vi umas soluções embarcadas que a DLL é menor que a atual, mesmo usando a wkhtmltopdf Caso alguem tenha interesse em implementar. @carloscds sugiro um HelpWanted aqui

**Comment by carloscds** [comment]
@olavorn Melhor incluir no pacote, senão aumenta a complexidade do uso. Não faz sentido eu ter que instalar um novo pacote só para imprimir.

**Comment by olavorn** [comment]
Só pra imprimir o HTML, creio que deve ser built-in. A minha preocupação é o tamanho da dll. Enquanto uma vai ficar bem pequena, a outra PDF vai ser grande. Uns 50 MB no mínimo. E nem todo mundo vai usar o boleto em PDF, ou vai?

**Comment by olavorn** [comment]
Podemos fazer ele entregar uma build FULL só pelo BoletoNetCore.PDF e pra quem quer só HTML, usa só o BoletoNetCore. Ainda assim, precisariamos de dois pacotes, ou vc acha que o tamanho não vai ser problema?

**Comment by carloscds** [comment]
@olavorn Somente HTML da para modificar, a boleto SEMPRE deve ser emitido em PDF. Não concordo em ter uma build separada para isto. Vamos aguardar os outros se pronunciarem.

**Comment by olavorn** [comment]
Entendi. Se é questão da segurança, ok. Embora PDF também seja possível modificar.
Teriamos que ver formas de diminuir o tamanho do pacote final então... Aceitamos idéias.

**Comment by carloscds** [comment]
@olavorn Não acredito que o pacote aumentará muito!

**Comment by igorocampos** [comment]
Olá a todos, se me permitem, posso deixar minha opinião como usuário desktop:
> Façam pacotes nuget separados, por favor!

O tamanho da DLL é algo que tem bastante peso na instalação e atualização dos usuarios desktop. E isso não é apenas na ordem de 23MB mencionados, uma biblioteca com mais de 5MB já se torna um peso grande para a não utilização da mesma.

Eis algumas vantagens da separação:
- Maior abrangência do uso do projeto por quem não gera PDF dos boletos, ou pelos menos maior contentamento destes visto que ninguém curte ter um monte de código embutido que nunca será utilizado.
- Possibilidade de utilização de outras bilbliotecas (pagas ou não) à escolha de quem utiliza o projeto. No meu caso por exemplo, poderíamos utilizar uma biblioteca de geração de PDF que já utilizamos no sistema, mas que não tem conversão direta de HTML para PDF, fazendo com que primeiro gere-se uma imagem do HTML e depois coloque a mesma no PDF, mesmo que isso signifique perda de qualidade, pois neste caso, esse não é o foco do nosso sistema.

Enfim, o projeto ficará mais permissivo caso sejam feitos pacotes separados.


Quanto ao comentário:
> Pense em quem ja usa a ferramenta, ai migra para o Core e precisa instalar um pacote para gerar PDF ?

Não vejo problema nisso, faz parte da migração e instalar 2 pacotes no lugar de 1 não é nada dificil.

Mas se isso for realmente crucial, pode ser feito o que o @olavorn disse:
> Podemos fazer ele entregar uma build FULL só pelo BoletoNetCore.PDF e pra quem quer só HTML, usa só o BoletoNetCore.

**Comment by olavorn** [comment]
@rafd75 , @carloscds 

Para usuários do .net core, realmente percebo que há certas escolha de padrões e costumes que divergem um pouco da visão e do ambiente o qual a versão original do projeto BoletoNet foi concebida. Mas no sentido de abraçar o novo, penso que algumas abordagens precisam também ganhar uma nova forma. A do uso do BoletoNetCore.Pdf certamente eu entendo que seria uma dessas. 

Por isso, peço pra que vc @carloscds reconsidere a possibilidade de separar em 2 pacotes e seguirmos dessa forma. O post do @igorocampos se não tivesse o nome dele, eu poderia reconhecer como algo que eu teria escrito. rsrsrs

**Comment by rafd75** [comment]
@olavorn ... boa tarde!

Já que um novo projeto foi criado (mantendo o Boleto2Net isolado), não vejo problema nenhum em alterar o que for necessário (assim como eu fiz, quando entreguei a primeira versão do Boleto2Net para o Carlão) ... 

Ou seja, não quebrou nada para quem estava usando o BoletoNet e a migração ficou a critério de cada um.

Considero que esse novo projeto é o momento ideal para qualquer mudança, seja simples ou profunda. 

O que pode ser feito, é uma documentação do "como migrar do Boleto2Net para BoletoNetCore" com um passo a passo, e exemplo de código de como fazer a impressão em pdf (ainda que em outro projeto).

Com relação ao meu projeto aqui (como uso a ferramenta) = Na verdade, trabalho principalmente com o Visual FoxPro (utilizo a DLL deste projeto através da classe proxy)... Então, por hora, vou seguir no Boleto2Net mesmo.

**Comment by igorocampos** [comment]
@carloscds 	que tipo de ajuda gostaria neste issue?

Para fazer 1 pacote separado atualmente, basta adicionar a tag em cada `csproj`
```xml
<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
```

desta maneira quando o projeto em questão for compilado o arquivo correspondente aparecerá na pasta `bin` do mesmo.

Aqui fiz o teste, adicionando a tag nos arquivos `BoletoNetCore.Pdf.csproj` e `BoletoNetCore.csproj` e os arquivos
- BoletoNetCore.Pdf.1.0.0.nupkg
- BoletoNetCore.1.0.0.nupkg

foram gerados com sucesso (bastaria agora fazer o upload dos mesmos).

**Comment by olavorn** [comment]
@igorocampos você pode fazer um PR com isso?

**Comment by igorocampos** [comment]
#29

**Comment by carloscds** [comment]
@igorocampos So coloca no doc que precisa instalar este pacote para gerar PDF.

**Comment by igorocampos** [comment]
Você quer dizer no `README.md` mesmo né? Talvez seja interessante já ter o link do nuget de ambos pacotes, quando mencionar a instalação do pacote para gerar PDF, faz-se um link para a nuget dele.
