### ISSUE TITLE
Geração de PDF em lista de boletos

### ISSUE THREAD

**Issue by eduardogerentklein** [BoletoNet/BoletoNetCore#226]
Boa tarde,

Lendo o [documento de migração](https://github.com/BoletoNet/BoletoNetCore/blob/master/migracao.md) "Na função "new BoletoBancario().MontaBytesListaBoletosPDF()" - Esta não está mais presente no BoletoNetCore, portanto adicionei um substituto para ele, "FuncoesBoleto.GeraPDFBoletos()", que retorna um byte[] com os arquivos PDFs.
OBS.: Você terá que adicionar o pacote nuget "BoletoNetCore.Pdf" ao projeto para usar essa função."

Não consegui localizar o método GeraPDFBoletos na qual foi referido, se possível gostaria de uma orientação, obrigado.

**Comment by carloscds** [comment]
@eduardogerentklein Na ideia incial a geracao do PDF ficou fora do projeto, retornando somente o HTML. Eu, por exemplo, uso outra ferramenta para gerar o PDF.

**Comment by eduardogerentklein** [comment]
Entendi, no caso uma saída seria utilizar o método  ImprimirCarnePdf do BoletoNetCore.QuestPdf? 

Obs.: Obrigado pela resposta rápida :)
