### ISSUE TITLE
Campo Livre (deve conter 25 dígitos.) - Banco Caixa

### ISSUE THREAD

**Issue by Gabriel-Cordeiro** [BoletoNet/BoletoNetCore#228]
Olá pessoal,

Comecei a utilizar essa biblioteca há uma semana e não estou conseguindo gerar o boleto para caixa, mesmo utilizando o código dos testes acabo com o erro abaixo

![image](https://user-images.githubusercontent.com/15033284/221045000-40f7780b-3ba3-4153-a3be-54a742f6c7cd.png)

Esse é o código que fiz copiando o exemplo dos testes, possuo o código final com os dados reais, porém enfrento o mesmo erro, não sei o que fazer para resolver.

var contaBancaria = new ContaBancaria
            {
                Agencia = "1234",
                DigitoAgencia = "X",
                Conta = "123456",
                DigitoConta = "X",
                CarteiraPadrao = "SIG14",
                TipoCarteiraPadrao = TipoCarteira.CarteiraCobrancaSimples,
                TipoFormaCadastramento = TipoFormaCadastramento.ComRegistro,
                TipoImpressaoBoleto = TipoImpressaoBoleto.Empresa
            };
            banco.Beneficiario = new Beneficiario
            {
                CPFCNPJ = "86.875.666/0001-09",
                Nome = "Beneficiario Teste",
                Codigo = "123456",
                CodigoDV = "01" //Se eu não informar, outro erro aparece, dizendo que não informei o digito do beneficiario,
                CodigoTransmissao = String.Empty,
                Endereco = new Endereco
                {
                    LogradouroEndereco = "Rua Teste do Beneficiário",
                    LogradouroNumero = "789",
                    LogradouroComplemento = "Cj 333",
                    Bairro = "Bairro",
                    Cidade = "Cidade",
                    UF = "SP",
                    CEP = "65432987"
                },
                ContaBancaria = contaBancaria
            };
            banco.FormataBeneficiario();

            var boleto = new Boleto(banco)
            {
                DataVencimento = DateTime.Now.AddDays(1),
                ValorTitulo = 5,
                NossoNumero = "6",
                NumeroDocumento = "BO123456F",
                EspecieDocumento = TipoEspecieDocumento.DM,
                Pagador = new Pagador
                {
                    CPFCNPJ = "443.316.101-28",
                    Nome = "Pagador Teste PF",
                    Observacoes = "Matricula 678/9",
                    Endereco = new Endereco
                    {
                        LogradouroEndereco = "Rua Testando",
                        LogradouroNumero = "456",
                        Bairro = "Bairro",
                        Cidade = "Cidade",
                        UF = "SP",
                        CEP = "56789012"
                    }
                }
            };
            
            boleto.ValidarDados();

**Comment by Gabriel-Cordeiro** [comment]
Código "real":

![image](https://user-images.githubusercontent.com/15033284/221045543-f3cbc617-bc48-46ff-a6d1-b60a2259905d.png)

![image](https://user-images.githubusercontent.com/15033284/221045599-8c2e7dae-267b-458c-8fb8-266eeadd96b6.png)

**Comment by carloscds** [comment]
@Gabriel-Cordeiro ME parece que o seu campo "nosso numero" esta incorreto, pois tem apenas um digito.

**Comment by Gabriel-Cordeiro** [comment]
> @Gabriel-Cordeiro ME parece que o seu campo "nosso numero" esta incorreto, pois tem apenas um digito.

Então, olhando os testes da Caixa, é informado um numero de um digito apenas 

![image](https://user-images.githubusercontent.com/15033284/221246376-3a73f585-7e01-402e-8202-834f61075d4a.png)

**Comment by Gabriel-Cordeiro** [comment]
O código DV era 01, mudei para 1 e resolveu o problema.
