### ISSUE TITLE
Geração do PDF

### ISSUE THREAD

**Issue by gmorbi** [BoletoNet/BoletoNetCore#230]
Olá,
Estou com uma dúvida, na rotina que eu possuo, já tenho a geração de todos os dados do boleto, inclusive do registro etc. A princípio, a implementação da biblioteca do boletonet, é para auxiliar apenas para gerar o base64 do PDF. Visto que já possuo toda a rotina de geração externa. Estou encontrando uma certa dificuldade para gerar apenas o PDF desse boleto de forma válida.
Cheguei a olhar o projeto de testes, onde exemplifica a implementação, mas no meu caso, que eu possuo linha digitavel, código de barras, não funciona, vi que essas propriedades por exemplo, não recebem valor.
Cheguei a procurar outra forma de fazer para atender o meu caso, mas infelizmente não encontrei.

Desde já agradeço.

**Comment by carloscds** [comment]
@gmorbi Nao entendi o problema!Você nao consegue gerar o boleto em PDF passando os dados ?

**Comment by gmorbi** [comment]
Não é bem um problema, acredito mais que seja dúvida minha, posso estar fazendo algo errado até.
Eu quero gerar o boleto em PDF passando todos os dados.

**Comment by gmorbi** [comment]
Consegui resolver, estava faltando passar mais alguns parâmetros, por isso o PDF estava aparecendo incompleto.
