### ISSUE TITLE
Não encontro propriedade para preencher agencia / codigo beneficiario (bradesco)

### ISSUE THREAD

**Issue by thiagocorreabotelho** [BoletoNet/BoletoNetCore#235]
Pessoal, boa tarde!

Estou tendo dificuldade no layout do bradesco para achar a parte para preenchimento da agencia e o código do beneficiario conforme a imagem abaixo:

![image](https://user-images.githubusercontent.com/99252640/228934496-4e9be29a-1b2d-4f82-b9c2-adf2bf5f6c4c.png)

Poderia me ajudar?

**Comment by thiagocorreabotelho** [comment]
?

**Comment by carloscds** [comment]
@thiagocorreabotelho Da uma olhada nos projetos de testes.
