### ISSUE TITLE
Html Boleto 

### ISSUE THREAD

**Issue by thiagocorreabotelho** [BoletoNet/BoletoNetCore#241]
Pessoal, tenho uma api que consome o serviço BoletoNetCore e retorna o html do boleto.
Tem como ajustar esse layout do boleto? Seria na aplicações de vcs ou isso é feito por parte do cliente?

![image](https://user-images.githubusercontent.com/99252640/233473334-aadeda75-5edd-4d8a-ab58-a8ce5aefe76f.png)

**Comment by carloscds** [comment]
@thiagocorreabotelho Ja tentou gerar um PDF e retornar, inclusive é mais seguro.

**Comment by thiagocorreabotelho** [comment]
> @thiagocorreabotelho Ja tentou gerar um PDF e retornar, inclusive é mais seguro.

Vou verificar.
