### ISSUE TITLE
Problema gerar número do boleto

### ISSUE THREAD

**Issue by thiagocorreabotelho** [BoletoNet/BoletoNetCore#244]
Pessoal estou com um problema ao gerar o número do boleto, quando coloco por exemplo o número do boleto no app para pagar ou tento ler o código de barra ele da um erro dizendo que o código não pode ser validado.

Para gerar o boleto fiz da seguinte forma:

````CSharp

 public static Boleto GerarBoleto(IBanco banco, DadosBoletoBradesco dadosBoleto, int i, string aceite, int NossoNumeroInicial)
        {
            try
            {


                int _contador = 1;
                int _proximoNossoNumero = 1;

                if (aceite == "?")
                    aceite = _contador % 2 == 0 ? "N" : "A";

                var boleto = new Boleto(banco)
                {
                    Pagador = GerarPagador(dadosBoleto),
                    DataEmissao = DateTime.Now.AddDays(-3),
                    DataProcessamento = DateTime.Now,
                    DataVencimento = DateTime.Parse(dadosBoleto.DataVencimentoDocumento),
                    ValorTitulo = dadosBoleto.Beneficiario.BeneficiarioContaBancaria.Valor,
                    NossoNumero = dadosBoleto.NossoNumeroBoleto.Substring(0, 11),
                    NumeroDocumento = dadosBoleto.Participante.Chave.Substring(10, 13),
                    EspecieDocumento = TipoEspecieDocumento.DM,
                    Aceite = aceite,
                    CodigoInstrucao1 = "11",
                    CodigoInstrucao2 = "22",
                    AvisoDebitoAutomaticoContaCorrente = "2",
                    MensagemArquivoRemessa = string.Empty,
                    NumeroControleParticipante = "CHAVEPRIMARIA" + _proximoNossoNumero,
                    ImprimirValoresAuxiliares = true,
                    
            };

                boleto.ValidarDados();
                _contador++;
                _proximoNossoNumero++;

                return boleto;
            }
            catch (Exception ex)
            {
                throw;
            }
        }

````

Quando ele retorna a numeração do boleto ele gera: **23792.37304 93102.000002 80239.290903 1 93340000140498** e o numero correto para gerar teria que ser: **xxxx.37304 93102.000002 08023.929006 6 93340000140498**

pelo que analisei aqui o b.o esta na formação dos grupos:

        GRUPO1 23792.37304 -- Certo
	GRUPO2 93102.000002 -- Certro
	GRUPO3 80239.290903 -- Errado
	GRUPO4 1 -- Errado
	GRUPO5 93340000140498 -- Certo
	
Não entendi muito bem essa parte de gerar o código, alguém consegue me auxiliar?

**Comment by thiagocorreabotelho** [comment]
Gera o layout normalmente porém o b.o esta no número para pagar e consequentemente o codigo de barras.
Já olhei os teste tb mesmo assim nao esta dando certo.

**Comment by carloscds** [comment]
@thiagocorreabotelho Isto ocorre por alguma configuyracao incorreta, valide os dados com o banco, tipo convenio, carteira.
