### ISSUE TITLE
Geração boleto 

### ISSUE THREAD

**Issue by gmorbi** [BoletoNet/BoletoNetCore#248]
Recentemente implementei a biblioteca do boletonetcore, e passei a fazer uso dela, para renderizar o pdf dos boletos.
Hoje eu possou uma rotina que realiza a geração de todos os dados boleto, essa rotina gera boletos consistentes e que já até foram homologados pelos bancos (Itaú e Santander)
Basicamente eu pego o retorno dessa minha rotina, onde contém todas as informações do boleto que desejo renderizar, e faço a chamada de validação dos dados.
Porém notei uma inconsistência na geração dos boletos renderizados, tanto no Itaú quanto no Santander, em relação aos dados que eu passo. A inconsistência encontrada, está na linha digitável e no código de barras. As informações que eu tenho, gerados pela minha rotina não coincidem com a apresentada no boleto. Não sei informar se é algum parâmetro que eu esteja faltando passar ou algum peso para o cálculo do módulo do dígito verificador.
Mas eu passo inclusive a linha digitável nos parâmetros, mas quando o boleto é validado essa linha é substituída. Esse problema ocorre tanto na geração de boletos Itaú quanto Santander.

**Comment by carloscds** [comment]
@gmorbi O problema esta no PDF ? Quando vc pega o HTML somente a linha esta correta ?

**Comment by thiagocorreabotelho** [comment]
Olá! Pelo que entendi do seu problema, você está trabalhando em um código que valida dados de uma conta bancária e está preocupado com a correta atribuição dos dados da conta e do dígito da conta.

Nesse sentido, é fundamental que você se certifique de que os dados da conta e do dígito da conta estejam sendo atribuídos de forma separada e correta. Mesmo que você tenha o retorno da linha digitável, é importante lembrar que o método ValidarDados fará o cálculo novamente para gerar a linha digitável mesmo que você tenha o retorno do banco dessa linha.

Além disso, é necessário ficar atento na formatação dos dados, como o CodigoDV e a conta, que devem estar de acordo com as especificações para a validação da conta bancária. Outro ponto importante a ser considerado é a validação da data de vencimento, que deve estar correta para que a validação dos dados seja efetiva.
Eu falo para você sobre a conta, pois antes eu estava mandando a conta junta com o dv ai dava linha digitavel diferente.
Tem que ser a conta separada do digito.

**Comment by gmorbi** [comment]
@carloscds O problema está em ambos, PDF e HTML. A linha digitável está sendo substituída.

@thiagocorreabotelho Hoje tenho uma rotina que gera o boleto, porém não renderiza o PDF. A implementação que eu fiz com a biblioteca, é para renderizar o boleto, sendo assim, estou utilizando todos os dados que já foram gerados.

**Comment by thiagocorreabotelho** [comment]
> @carloscds O problema está em ambos, PDF e HTML. A linha digitável está sendo substituída.
> 
> @thiagocorreabotelho Hoje tenho uma rotina que gera o boleto, porém não renderiza o PDF. A implementação que eu fiz com a biblioteca, é para renderizar o boleto, sendo assim, estou utilizando todos os dados que já foram gerados. 

Entendi.
Bom de qualquer forma dá um bizu no debugar .
Falo isso porque eu fiz um trabalho que eu já tinha uma rotina que volta todos os dados e minha divergência na verdade foi esses dados.
Aí passar esses dados quando vc instanciar esse projeto.

Tipo é como se fosse reemprimir o boleto já tenho uma rotina para retornar tlg.

**Comment by carloscds** [comment]
@gmorbi A linha digitável com problemas é alguma configuração incorreta, por exemplo codigo do convênio ou carteira.

**Comment by gmorbi** [comment]
> 

Então é exatamente isso que tenho aqui. A rotina gera o boleto, registra e tudo mais. E é algo antigo que já está em funcionamento, homologado e tudo mais. 
Estamos migrando aos poucos para o boletonet.

**Comment by thiagocorreabotelho** [comment]
hmmm tem um endpoint de api que ta na pasta WebAPI desse component e se eu não estou engando é do Itau.
Nele se algo der errado ele te fala qual informação esta faltando, da um bizu.
Faz um teste baixa esse projeto ai na sua máquina, passa no swgger os mesmo dado dessa sua rotina e manda gerar o boleto, se der errado ele vai te devolver o possível erro.

Eu estava batendo errado com os dados e o Carlos me orientou sobre essas coisas faltante.

**Comment by thiagocorreabotelho** [comment]
> > 
> 
> Então é exatamente isso que tenho aqui. A rotina gera o boleto, registra e tudo mais. E é algo antigo que já está em funcionamento, homologado e tudo mais. Estamos migrando aos poucos para o boletonet.

meu caso foi o mesmo rs tinha ja um serviço antigo que uma empresa descontinuou rs

**Comment by gmorbi** [comment]
> @gmorbi A linha digitável com problemas é alguma configuração incorreta, por exemplo codigo do convênio ou carteira.

@carloscds  vou revisar novamente esses parâmetros. Obrigado!

**Comment by gmorbi** [comment]
> hmmm tem um endpoint de api que ta na pasta WebAPI desse component e se eu não estou engando é do Itau. Nele se algo der errado ele te fala qual informação esta faltando, da um bizu. Faz um teste baixa esse projeto ai na sua máquina, passa no swgger os mesmo dado dessa sua rotina e manda gerar o boleto, se der errado ele vai te devolver o possível erro.
> 
> Eu estava batendo errado com os dados e o Carlos me orientou sobre essas coisas faltante.

Vou dar uma olhada também. Obrigado @thiagocorreabotelho

**Comment by thiagocorreabotelho** [comment]
Depois nos fala se deu certo. 😉

**Comment by gmorbi** [comment]
Bom do Itaú consegui resolver, era um problema na rotina, ela quem estava gerando errado e por esse motivo, divergia as linhas digitáveis, corrigi a rotina e passou a gerar semelhante. 
Do Santander estou com o problema semelhante, revisei todos os campos, o que notei de diferença é o campo livre que está sendo gerado sem o nosso número inteiro, estou passando um valor e no momento do cálculo ele está substituindo.

**Comment by gmorbi** [comment]
Vou encerrar a issue, pois acredito que o problema no santander é semelhante ao do Itaú. 
Muito obrigado a todos pela ajuda!

**Comment by thiagocorreabotelho** [comment]
> Vou encerrar a issue, pois acredito que o problema no santander é semelhante ao do Itaú. 
> Muito obrigado a todos pela ajuda!

Show de bola, qualquer coisa é só chamar.
