### ISSUE TITLE
Como utilizar o wkhtmltopdf em aplicação docker (linux)?

### ISSUE THREAD

**Issue by danilobreda** [BoletoNet/BoletoNetCore#25]
Estava querendo gerar os boletos em pdf porem vi que é utilizado um binario chamado wkhtmltopdf.
Gostaria de saber qual a maneira de utilizar ele em linux (docker).
Eu precisaria instalar os binários via apt-get?

**Comment by jlfjunior** [comment]
@danilobreda você passou por esse problema ? 
System.ComponentModel.Win32Exception (13): Permission denied

**Comment by danilobreda** [comment]
@jlfjunior acredito que tenha haver com questão de permissionamento, ou até mesmo qual o usuario a instalalção do dotnet foi feito... Mas lembra que o wkhtmltopdf é um executavel, o dotnet vai subir esse executavel e pegar a resposta dele que é um pdf no final das contas... então vc tem q ter permissão nas pastas td certinho pra executar isso.

Você está tentando rodar no docker? se sim, não era para ter esse problema não.

**Comment by jlfjunior** [comment]
@danilobreda estou rodando em uma instância EC2
