### ISSUE TITLE
[Itaú] Atribuir código de barras retornado do banco

### ISSUE THREAD

**Issue by thiagocorreabotelho** [BoletoNet/BoletoNetCore#264]
Pessoal, estou enfrentando um novo desafio aqui e gostaria de saber se alguém pode me ajudar. 
Desenvolvi uma lógica para registrar boletos no banco Itaú e, ao receber a resposta em meu response, obtenho a linha digitável e o código de barras com seus respectivos valores.
Gostaria de saber se há alguma maneira de usar esses valores diretamente ao invés de recalcula o código de barras no projeto BoletoNetCore. Dessa forma, eu poderia utilizar a linha digitável e o código de barras obtidos para montar o meu boleto.

**Comment by carloscds** [comment]
@thiagocorreabotelho Atualmente não é possível, mas isto pode ser alterado. Se puder, faça a alteração e envie um PR.
