### ISSUE TITLE
Número do Convênio Líder

### ISSUE THREAD

**Issue by trappivan** [BoletoNet/BoletoNetCore#269]
Não to achando algo equivalente dentro do boleto, qual seria o nome da variavel equivalente a esse valor do numero do convênio líder ?

**Comment by trappivan** [comment]
@carloscds Banco do brasil, possuo os seguintes valores, porém nenhum deles se chama convênio, por isso a dúvida

```
public int CodigoMoeda { get; set; } = 9;
        public string EspecieMoeda { get; set; } = "R$";
        public int QuantidadeMoeda { get; set; }
        public string ValorMoeda { get; set; } = string.Empty;
        public TipoMoeda TipoMoeda { get; set; } = TipoMoeda.REA;
        public TipoEspecieDocumento EspecieDocumento { get; set; }
        public string NossoNumero { get; set; } = string.Empty;
        public string NossoNumeroDV { get; set; } = string.Empty;
        public string NossoNumeroFormatado { get; set; } = string.Empty;
        public TipoCarteira TipoCarteira { get; set; } = TipoCarteira.CarteiraCobrancaSimples;
        public string Carteira { get; set; } = string.Empty;
        public string VariacaoCarteira { get; set; } = string.Empty;
        public string CarteiraComVariacao
        {
            get
            {
                if (!string.IsNullOrEmpty(Carteira) && !string.IsNullOrEmpty(VariacaoCarteira))
                {
                    return Carteira + "/" + VariacaoCarteira;
                }
                return Carteira + VariacaoCarteira;
            }
        }
        public string CarteiraImpressaoBoleto { get; set; } = string.Empty;
        public DateTime DataProcessamento { get; set; } = DateTime.Now;
        public DateTime DataEmissao { get; set; } = DateTime.Now;
        public DateTime DataVencimento { get; set; }
        public DateTime DataCredito { get; set; }
        public string NumeroDocumento { get; set; } = string.Empty;
        public string NumeroControleParticipante { get; set; } = string.Empty;
        public string Aceite { get; set; } = "N";
        public string UsoBanco { get; set; } = string.Empty;
        public bool ImprimirMensagemInstrucao { get; set; }
        public decimal ValorTitulo { get; set; }
        public bool ImprimirValoresAuxiliares { get; set; }
        public decimal ValorPago { get; set; }
        public decimal ValorPagoCredito { get; set; }
        public decimal ValorDesconto { get; set; }
        public decimal ValorTarifas { get; set; }
        public decimal ValorOutrasDespesas { get; set; }
        public decimal ValorOutrosCreditos { get; set; }
        public decimal ValorIOF { get; set; }
        public decimal ValorAbatimento { get; set; }
        public decimal ValorJurosDia { get; set; }
        public decimal PercentualJurosDia { get; set; }
        public DateTime DataJuros { get; set; }
        public TipoJuros TipoJuros { get; set; }
        public decimal ValorMulta { get; set; }
        public decimal PercentualMulta { get; set; }
        public DateTime DataMulta { get; set; }
        public TipoCodigoMulta TipoCodigoMulta { get; set; } = TipoCodigoMulta.Valor;
        public DateTime DataDesconto { get; set; }
        public string EmiteBoletoDebitoAutomatico { get; set; } = "N";
        public string RateioCredito { get; set; }
        public string AvisoDebitoAutomaticoContaCorrente { get; set; }
        public string QuantidadePagamentos { get; set; }
        public string BancoCobradorRecebedor { get; set; }
        public string AgenciaCobradoraRecebedora { get; set; }
        public string AgenciaDebitada { get; set; }
        public string ContaDebitada { get; set; }
        public string DigitoVerificadorAgenciaDebitada { get; set; }
        public string DigitoVerificadorAgenciaContaDebitada { get; set; }
        public string CodigoMovimentoRetorno { get; set; } = "01";
        public string DescricaoMovimentoRetorno { get; set; } = string.Empty;
        public string CodigoMotivoOcorrencia { get; set; } = string.Empty;
        public string DescricaoMotivoOcorrencia => string.Join(", ", ListMotivosOcorrencia.Where((string x) => x != string.Empty).ToArray());
        public IEnumerable<string> ListMotivosOcorrencia { get; set; } = Enumerable.Empty<string>();
        public TipoCodigoProtesto CodigoProtesto { get; set; }
        public int DiasProtesto { get; set; }
        public TipoCodigoBaixaDevolucao CodigoBaixaDevolucao { get; set; } = TipoCodigoBaixaDevolucao.BaixarDevolver;
        public int DiasBaixaDevolucao { get; set; } = 60;
        public string CodigoInstrucao1 { get; set; } = string.Empty;
        public string ComplementoInstrucao1 { get; set; } = string.Empty;
        public string CodigoInstrucao2 { get; set; } = string.Empty;
        public string ComplementoInstrucao2 { get; set; } = string.Empty;
        public string CodigoInstrucao3 { get; set; } = string.Empty;
        public string ComplementoInstrucao3 { get; set; } = string.Empty;
        public string MensagemInstrucoesCaixa { get; set; } = string.Empty;
        public string MensagemInstrucoesCaixaFormatado { get; set; } = string.Empty;
        public string MensagemArquivoRemessa { get; set; } = string.Empty;
        public string RegistroArquivoRetorno { get; set; } = string.Empty;
        public int? DiasLimiteRecebimento { get; set; }
        public int Distribuicao { get; set; }
        public IBanco Banco { get; set; }
        public Pagador Pagador { get; set; } = new Pagador();
        public Pagador Avalista { get; set; } = new Pagador();
        public CodigoBarra CodigoBarra { get; } = new CodigoBarra();
        public ObservableCollection<GrupoDemonstrativo> Demonstrativos { get; } = new ObservableCollection<GrupoDemonstrativo>();
        public string ParcelaInformativo { get; set; } = string.Empty;

```

**Comment by carloscds** [comment]
@trappivan Convenio é uma propriedade da ContaBancaria: BoletoNetCore/Boleto/ContaBancaria.cs

**Comment by trappivan** [comment]
`using BoletoNetCore.Exceptions;
namespace BoletoNetCore
{
    public class ContaBancaria
    {
        public TipoCarteira TipoCarteiraPadrao { get; set; } = TipoCarteira.CarteiraCobrancaSimples;
        public string CarteiraPadrao { get; set; } = string.Empty;
        public string VariacaoCarteiraPadrao { get; set; } = string.Empty;
        public string CarteiraComVariacaoPadrao
        {
            get
            {
                if (!string.IsNullOrEmpty(CarteiraPadrao) && !string.IsNullOrEmpty(VariacaoCarteiraPadrao))
                {
                    return CarteiraPadrao + "/" + VariacaoCarteiraPadrao;
                }
                return CarteiraPadrao + VariacaoCarteiraPadrao;
            }
        }
        public string Agencia { get; set; } = string.Empty;
        public string DigitoAgencia { get; set; } = string.Empty;
        public string Conta { get; set; } = string.Empty;
        public string DigitoConta { get; set; } = string.Empty;
        public string OperacaoConta { get; set; } = string.Empty;
        public TipoFormaCadastramento TipoFormaCadastramento { get; set; } = TipoFormaCadastramento.ComRegistro;
        public TipoImpressaoBoleto TipoImpressaoBoleto { get; set; } = TipoImpressaoBoleto.Empresa;
        public TipoDocumento TipoDocumento { get; set; } = TipoDocumento.Tradicional;
        public string LocalPagamento { get; set; } = "PAGÁVEL EM QUALQUER BANCO.";
        public string MensagemFixaTopoBoleto { get; set; } = "";
        public string MensagemFixaPagador { get; set; } = "";
        public int CodigoBancoCorrespondente { get; set; }
        public string NossoNumeroBancoCorrespondente { get; set; }
        public TipoDistribuicaoBoleto TipoDistribuicao { get; set; } = TipoDistribuicaoBoleto.ClienteDistribui;
        public void FormatarDados(string localPagamento, string mensagemFixaTopoBoleto, string mensagemFixaPagador, int digitosConta)
        {
            LocalPagamento = localPagamento;
            MensagemFixaTopoBoleto = mensagemFixaTopoBoleto;
            MensagemFixaPagador = mensagemFixaPagador;
            string agencia = Agencia;
            if (agencia.Length > 4)
            {
                throw BoletoNetCoreException.AgenciaInvalida(agencia, 4);
            }
            Agencia = agencia.PadLeft(4, '0');
            string conta = Conta;
            if (conta.Length > digitosConta)
            {
                throw BoletoNetCoreException.ContaInvalida(conta, digitosConta);
            }
            Conta = conta.PadLeft(digitosConta, '0');
        }
    }
}`

porem o meu conta bancária nao possui convênio

**Comment by carloscds** [comment]
@trappivan Este é o codigo fonte do projeto:
![image](https://github.com/BoletoNet/BoletoNetCore/assets/1697221/664ea723-fea1-40e5-bfb9-e3a44debc185)

Se o seu nao tem, verifica a origem do codigo.

**Comment by trappivan** [comment]
opa deu certo, teve que atualizar nuget do BoletoNetCore. Obrigado pela ajuda, salvou minhas horas extras!
