### ISSUE TITLE
Daycoval - Registro de nota fiscal a cada Detalhe

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/BoletoNetCore#274]
Boa noite,

Estou fazendo a implementação do Daycoval no meu tempo livre (vai demorar...rs).

Entretanto, lendo o manual (anexado aqui) me deparei com o seguinte registro:
![image](https://github.com/BoletoNet/BoletoNetCore/assets/15945003/0e78c405-d3d4-4cc8-a34d-495982050044)

Basicamente, preciso preencher uma nova linha a cada detalhe com os dados da nota fiscal. É obrigatório.

Não sei como proceder nesse caso.

Manual:
[Manual M. 707 - Banco Daycoval Jun-21 (003).pdf](https://github.com/BoletoNet/BoletoNetCore/files/12045347/Manual.M.707.-.Banco.Daycoval.Jun-21.003.pdf)

E-mail do banco:
![image](https://github.com/BoletoNet/BoletoNetCore/assets/15945003/2484dc75-e24b-424c-b62c-5f8359efd83b)

Meu código até o momento (toda ajuda é bem vinda):
[daycoval.zip](https://github.com/BoletoNet/BoletoNetCore/files/12045360/daycoval.zip)

**Comment by carloscds** [comment]
@marcosgerene este registro é obrigatorio ?

**Comment by marcosgerene** [comment]
Como descrito no e-mail acima, sim.

Por isso a duvida, infelizmente nao posso ignorar o registro.

**Comment by carloscds** [comment]
@marcosgerene Nao faz sentido isto ser obrigatorio, pois imagine que vc renegociou uma divida com cliente e precisa emviar boletos, nao terá uma NF para esta operacao.

**Comment by marcosgerene** [comment]
@carloscds Concordo e vou alem:

Sou prestador de serviços. Emito boleto. Não emito NFe, mas sim NFSe. Não me encaixo na regra.

Entretanto,suponhamos que seja obrigatorio e que em casos como o que citei eu deva informar somente zeros. Como proceder?

**Comment by carloscds** [comment]
@marcosgerene Sugiro você falar com o banco.

**Comment by marcosgerene** [comment]
@carloscds 

Já estou fazendo esse contato, só quero entender como eu poderia encaixar esse registro na estrutura do projeto.

**Comment by marcosgerene** [comment]
@carloscds 

Já estou fazendo esse contato, só quero entender como eu poderia encaixar esse registro na estrutura do projeto.

**Comment by carloscds** [comment]
@marcosgerene No projeto, qualquer alteracao no pode quebrar o que esta rodando, entao toda esta estrutura deverá ser opcional.

**Comment by marcosgerene** [comment]
@carloscds 

A estrutura é opcional em casos como você e eu descrevemos acima. Entretanto o banco pede que eu informe quando possível.

![image](https://github.com/BoletoNet/BoletoNetCore/assets/15945003/88202c2a-1754-45c9-916c-192fc2cd2b31)

O que estou buscando é saber qual a melhor forma de eu implementar isso usando o BoletoNetCore, ou isso não é possível?

**Comment by carloscds** [comment]
@marcosgerene Melhor forma é deixar tudo isto como opcional, par nao quebrar o que existe hoje.
