### ISSUE TITLE
Cecred/AILOS - Lote de remessa, campo Convênio esta com o numero do banco 

### ISSUE THREAD

**Issue by Hardshop18** [BoletoNet/BoletoNetCore#277]
Estava realizando a homologação para o banco AILOS CNAB 240, ao fazer a validação com o banco foi retornado o problema:
No registro Header de Lote a informação do convenio estava com a informação do numero do banco, verificado no fonte e estava assim:
`tregistroEdi.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 34, 20, 0, Codigo, ' ');`

Realizado a alteração para:
`tregistroEdi.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 34, 20, 0, Beneficiario.ContaBancaria.CodigoConvenio, ' ');`

Feita esta alteração com base no manual:
![manual_cnab_240_ailos](https://github.com/BoletoNet/BoletoNetCore/assets/60898897/d0d865b4-f19b-4f43-a5a8-feb1884bc698)

![manual_cnab_240_validacao_G007](https://github.com/BoletoNet/BoletoNetCore/assets/60898897/1e5f302a-6e05-48e4-a20b-b4f48942aa93)

**Comment by carloscds** [comment]
@Hardshop18 por favor, mande um PR com a alteracao.

**Comment by Hardshop18** [comment]
Feito o PR
