### ISSUE TITLE
Geração de PDF em 3.1 e 6.0

### ISSUE THREAD

**Issue by meirochun** [BoletoNet/BoletoNetCore#279]
Olá, dúvida rápida. Venho usado o BoletoNetCore para projetos netstandard2.1.
Recentemente estou trabalhando com 2 api's uma em 3.1 e outra em 6.0.
Não é possível mesmo utilizar a função de GerarArquivoPDF?

https://github.com/BoletoNet/BoletoNetCore/blob/44c2864761933984fff9a65904a68ddd25c1472c/BoletoNetCore.Pdf/BoletoNetCorePdfProxy.cs#L79C1-L87

**Comment by carloscds** [comment]
@meirochun É possivel, mas sugiro q vc faca um teste baixando o código.

**Comment by meirochun** [comment]
@carloscds Te atualizando. Utilizei o boletonetcore apenas para gerar pagador, boleto, etc... em relacao a gerar arquivo eu consegui gerar o HTML e utilizei outra lib para transformar em PDF, funcionou tambem.

Agradeco a atencao, se tiver alguma forma de gerar PDF em .net 6 com o boletonetcore me diga 🙏

**Comment by carloscds** [comment]
@meirochun Este pacote funciona em .NET 3.1 para cima: https://www.nuget.org/packages/HtmlToPDFCore

**Comment by meirochun** [comment]
@carloscds Realmente muito mais facil de implementar, se eu tiver oportunidade irei usar em futuros projetos/clientes!
