### ISSUE TITLE
Erro ao tentar utilizar IBanco na camada de DI

### ISSUE THREAD

**Issue by thiagocorreabotelho** [BoletoNet/BoletoNetCore#286]
Pessoal estou tendo problema em implementar o serviço do boleto em uma API que estou criando. Pode ser problema fácil de resolver mas que estou apanhando um pouco.

Criar uma api utilizando arquitetura limpa conforme o print:

![image](https://github.com/BoletoNet/BoletoNetCore/assets/99252640/289c8d85-60be-49b4-9aa0-e538d12f2bc3)

O problema que estou tendo é quando inicio o projeto, pois esta gerando o seguinte erro:
_`System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType:`_ 

Esse problema esta ocorrendo porque dentro do projeto de CrossCutting eu não injetei a interface do mesmo:

![image](https://github.com/BoletoNet/BoletoNetCore/assets/99252640/77484399-dc51-4f3d-9c16-41a15b92d392)

Deixei comentado, pois dentro do BoletoNetCore eu não consegui achar uma classe que herdasse iBanco e ao tentar colocar:

````cSharp
   services.AddScoped<IBanco, Banco>();
````
gera um outro erro dizendo que o classe Banco é static que não pode ser usada.
Não sei se estou dando uma viajada para utilizar iBanco.

Dentro do repositório eu utilizo o ibanco para instanciar de qual banco estamos falando na hora de renderizar o boleto. Por isso que preciso acessar esse cara de alguma forma.

![image](https://github.com/BoletoNet/BoletoNetCore/assets/99252640/e7747b93-7d4c-4ae9-92a9-4b94ecb50c61)

**Comment by carloscds** [comment]
@thiagocorreabotelho Mandei um PR para corrigir.

**Comment by thiagocorreabotelho** [comment]
Problema solucionado, fechando a issue.
