### ISSUE TITLE
O que faz com que o codigo de barras nao gere corretamente? 

### ISSUE THREAD

**Issue by glaucodiogo** [BoletoNet/BoletoNetCore#291]
Preenchi o json com todos os parametros e somente recebo as barras pequenas como na foto  :(
![image](https://github.com/BoletoNet/BoletoNetCore/assets/1531141/c18c0cf2-c8c2-4689-b5e0-4af8c9398566)

**Comment by carloscds** [comment]
@glaucodiogo Qual json vc preencheu ?

**Comment by carloscds** [comment]
@glaucodiogo Qual o banco ?

**Comment by glaucodiogo** [comment]
Eu percebi que o metodo de validação estava comentado no código. Tirei o comentário e funcionou a geração do cod barras normalmente

**Comment by glaucodiogo** [comment]
Eu percebi que o metodo de validação estava comentado no código. Tirei o comentário e funcionou a geração do cod barras normalmente
