### ISSUE TITLE
Falha ao GeraHtmlDeVariosBoletosParaEmail

### ISSUE THREAD

**Issue by tonborges** [BoletoNet/BoletoNetCore#30]
Ao tentar gerar o html para envio por e-mail estou tendo a exception abaixo, estou usando a versão 1.0.0-beta7; 
Unable to cast object of type 'System.String' to type 'System.Drawing.Bitmap'.

   at BoletoNetCore.Html.get_barra()
   at BoletoNetCore.BoletoBancario.GeraGraficosParaEmailOffLine(LinkedResource& lrImagemLogo, LinkedResource& lrImagemBarra, LinkedResource& lrImagemCodigoBarra)
   at BoletoNetCore.BoletoBancario.GeraHtmlDeVariosBoletosParaEmail(String textoNoComecoDoEmail, BoletoBancario[] arrayDeBoletos)
   at BoletoNetCore.BoletoBancario.GeraHtmlDeVariosBoletosParaEmail(BoletoBancario[] arrayDeBoletos)xt()

Alguém poderia me ajudar?

**Comment by tonborges** [comment]
Debugando o projeto da lib, encontrei o seguinte problema:

**'TypeConverter' is unable to convert 'System.Drawing.Bitmap' to 'System.Byte[]'.**

No método: **ConvertImageToByte(Image image)** 

Se essa for a causa do erro quando gerado o nuget podemos alterar o método para:

 **using (var ms = new MemoryStream())
                {
                    image.Save(ms, ImageFormat.Jpeg);
                    return ms.ToArray();
                }**

**Comment by olavorn** [comment]
@tonborges o caso é que a dependência original usava System.Drawing, que não era netStandard. Este snippet exige adicionar System.Drawing? Caso positivo, acho melhor procurar outra solução.

**Comment by tonborges** [comment]
@olavorn ele usa o System.Drawing sim, mas o mesmo já estava adicionado no projeto, fiz testes usando o netcoreapp2.2 e funcionou sem problemas aqui.

**Comment by olavorn** [comment]
É que no caso não era o System.Drawing original, mas sim o System.Drawing.Common, que é uma versão "desidratada" da System.Drawing que permite compatibilidade com outras plataformas.

**Comment by olavorn** [comment]
Mas legal que funciona! Vc pode fazer um PR pra gente avaliar?

**Comment by tonborges** [comment]
@olavorn Fiz o PR, podem avaliar :)

**Comment by olavorn** [comment]
@carloscds pode fechar a issue?

**Comment by carloscds** [comment]
@olavorn Por mim ok!

**Comment by olavorn** [comment]
Não sou maintainer, não tenho como fechar :/
