### ISSUE TITLE
Linha digitável não copiável

### ISSUE THREAD

**Issue by HalanRFOliveira** [BoletoNet/BoletoNetCore#325]
Olá. Espero encontrá-los bem.

Estou consumindo os pacotes e após gerar o html do boleto (MontaHtmlEmbedded) converti pra pdf.

O fato é que o 'MontaHtmlEmbedded' converte a linha digitável um uma imagem jpeg, impossibilitando o usuário de copiar e colar essa linha.

Há alguma alternativa no código pra isso ou é caso de PR?

Grato pelos esforços de vocês por manterem o projeto!

**Comment by carloscds** [comment]
@HalanRFOliveira Você pode usar esta propriedade: Boleto.CodigoBarra.LinhaDigitavel
