### ISSUE TITLE
Carteira 9/01 no Sicoob

### ISSUE THREAD

**Issue by Felipe-G-Melo** [BoletoNet/BoletoNetCore#327]
Queria fazer a implementação da carteira 9/01 do Siccob, alguém pode me ajudar por onde começar ?

**Comment by Felipe-G-Melo** [comment]
@carloscds já estou com a documentação em mãos, mas queria saber quais as váriaveis de carteira para carteira. Já fiz um fork e "implementei" a carteira 9 copiando a 2, apenas mudando o decorator para [CarteiraCodigo("9/01")].

**Comment by carloscds** [comment]
@Felipe-G-Melo basicamente é isto, agora é gerar o arquivio e validar com o banco.

**Comment by Felipe-G-Melo** [comment]
@carloscds ok, vou fazer alguns testes e enviar para validação do banco, estando tudo certo faço uma PR.

**Comment by Felipe-G-Melo** [comment]
@carloscds Fiz a implementação e quando fui validar com o banco eles falaram que não existe a carteira 9. Me passaram errado, a certa era a 1 que já esta implementada ;-;. Mas muito obrigado pela atenção.
