### ISSUE TITLE
Disponibilidade das PRs no nuget.org

### ISSUE THREAD

**Issue by victorvilella** [BoletoNet/BoletoNetCore#332]
Olá.

Possuo uma aplicação de que depende desta biblioteca para o seu correto funcionamento. Recentemente fiz algumas contribuições referente a solicitações dos usuários do meu sistema e notei que esse projeto não tem um workflow no Github que faz o deploy no NuGet.

Podemos ter algum workflow que faz esse deploy conforme os PRs são aprovados? Qual seria a melhor forma? Eu mesmo estou usando o nuget packages do Github pra eu conseguir gerar versões do meu sistema mas talvez seja mais interessante para todos nós termos uma versão oficial.

Obrigado desde já.

**Comment by carloscds** [comment]
@victorvilella O projeto gera um pacote no Myget a cada Build e dependendo do numero de atualizações no mês, geramos um pacote no nuget. Na home do projeto tem link para o Myget: https://www.myget.org/gallery/boletonetcorebuild

**Comment by victorvilella** [comment]
@carloscds Obrigado pela resposta. 

Eu não conhecia o myget. Também percebi que a versão que contém meus PRs já estão no nuget.org. Quando me preparei pra gerar uma versão para produção do meu projeto, meu gerenciador não havia sugerido nenhuma atualização da versão, por isso eu abri esta issue.

De qualquer forma, agradeço a atenção.
