### ISSUE TITLE
Integração via API com os bancos

### ISSUE THREAD

**Issue by victorvilella** [BoletoNet/BoletoNetCore#338]
Não sei se isso já foi discutido antes por aqui mas gostaria de ver se as pessoas poderiam gostar da ideia de criar funções dentro do projeto para fazer as operações bancárias diretamente com os bancos usando API REST ou SOAP (dependendo da instituição).

A ideia é emular o que o [ACBr](https://projetoacbr.com.br/) faz, que é criar uma abstração para facilitar a integração com os bancos.

Eu poderia desenvolver com alguns bancos ao longo do tempo. O que acham da ideia?

**Comment by carloscds** [comment]
@victorvilella @thiagocorreanet ja tentou montar um projeto assim.

**Comment by thiagocorreanet** [comment]
> @victorvilella @thiagocorreanet ja tentou montar um projeto assim.

Se quiser tomar como base: https://github.com/thiagocorreanet/BoletoAPI

**Comment by victorvilella** [comment]
Eu não sabia da existência desse projeto. Acredito que ele vá me atender quase que perfeitamente. Obrigado pelo feedback.

**Comment by thiagocorreanet** [comment]
> Eu não sabia da existência desse projeto. Acredito que ele vá me atender quase que perfeitamente. Obrigado pelo feedback.

Se você quiser reescrever me da um toque, faz um tempinho que fiz. Podemos fazer um refactor dele mirando no que você precisa. 👊🏻
