### ISSUE TITLE
Banco Daycoval

### ISSUE THREAD

**Issue by Ipojuca** [BoletoNet/BoletoNetCore#342]
Boa tarde, 

O banco Daycoval exige dos clientes que emitem NFe que enviem um registro adicional do CNAB400.

Eu implementei essa feature da seguinte forma:
Criei uma propriedade no Boleto onde informo os dados da NFe  sem nenhum prejuízo aos demais bancos.
Implementei na classe BancoDaycoval um Metodo GerarNFeRemessa que gera esse bendito registro no CNAB400.

Na Class ArquivoRemessa.GerarArquivoRemessa eu verifico se o Banco implementa o Metodo e então executo ele dessa forma não seria necessário mexer em todos os bancos.  

Uma outra forma possível seria colocar na interface Ibanco e implementar retornando nulo nos outros banco assim como foi feito com GerarMensagemRemessa. 

Gostaria de uma opinião antes de fazer um PR () 

https://github.com/Ipojuca/BoletoNetCore

**Comment by carloscds** [comment]
@Ipojuca Mande um PR para analisarmos as mudanças.
