### ISSUE TITLE
Arquivo Retorno

### ISSUE THREAD

**Issue by JoriveFB** [BoletoNet/BoletoNetCore#41]
Bom dia. Não consegui achar um exemplo para ler o arquivo de retorno. Estou tentando ler um do Bradesco mas não estou conseguindo, Mas pode ser um exemplo de outro banco também.

Desde já agradeço.

**Comment by carloscds** [comment]
@JoriveFB Da uma olhada aqui: https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net.Testes/BancoUniprimeTeste.cs

**Comment by JoriveFB** [comment]
@carloscds muito obrigado pelo apoio.
