### ISSUE TITLE
Notifiação do Banco SAFRA

### ISSUE THREAD

**Issue by olavorn** [BoletoNet/BoletoNetCore#46]
Chegou no nosso contato uma notificação do Banco SAFRA:

> Prezado Responsável,

> A AXUR representa o Banco Safra  em questões envolvendo violação de propriedade intelectual e fraudes na Internet.

> O Banco Safra é detentor dos direitos do uso da marca e nome comercial e Banco Safra, inscrita > no Instituto Nacional da Propriedade Industrial - INPI (www.inpi.gov.br) sob os números > > > > > 823231798, 816062129. Você deve estar ciente que Banco Safra é uma marca registrada para > > > identificar produtos, serviços, atividades e eventos relacionados ao Banco Safra.

> Constatamos que você hospedou conteúdo sensível relacionado ao Banco Safra no Git Hub sem ter obtido autorização. Ao utilizar a marca Banco Safra sem autorização, você está fazendo mal-uso da mesma, criando um risco de confusão entre usuários que buscam conteúdos provenientes do Banco Safra.

> Conteúdo infrator: https://github.com/BoletoNet/BoletoNetCore/commit/cc9ed47c996596b6ca78a38dd5e2d0669b694778

> Com base nas violações dos direitos do Banco Safra, de acordo com a Lei Federal Brasileira Nº 9.279, que trata dos direitos e obrigações referentes à propriedade industrial, solicitamos que você remova todo e qualquer conteúdo relacionado ao Banco Safra na URL acima.

> Em caso de recusa, silêncio ou não atendimento da solicitação acima anotada, serão adotadas as medidas administrativas e judiciais necessárias à proteção do direito violado.

> Sob pena de perjúrio, afirmamos que a AXUR está autorizada a agir em nome do Banco Safra  neste caso, e essa notificação está de acordo com a Lei Federal Brasileira n° 9.279/96 e com os órgãos internacionais que regulam os Direitos de Propriedade Intelectual.

> Caso você necessite informações adicionais ou prefira discutir esse assunto, por favor, não hesite em fazer contato através do endereço que consta na assinatura desta mensagem.

> Atenciosamente,

> AXUR Brand Abuse
legal@axur.com
Para mais informações acesse www.axur.com.

É mole?

**Comment by olavorn** [comment]
Minha resposta,

> Prezados,

> Na condição de membro contribuidor, mas não fundador, do projeto, respondo o posicionamento sem vínculo a responsabilidade de manutenção do conteúdo em questão, que é de terceiros. Dito isto, Necessitamos de informações adicionais. Não reconhecemos no conteúdo posto nenhuma informação sensível de qualquer propriedade do referido banco. O conteúdo publicado se trata de implementação para uso geral para confecção de boletos para ser utilizado por clientes do banco representado, sendo de completa e totalmente inofensivo a marca, pois não tem o objetivo de denegrir, apropriar ou expor ou lucrar com a instituição em nenhum sentido.

> Ademais, todas as informações ali postas estão inclusas em manuais para possibilitar justamente a implementação de conteúdos similares por diversas softwarehouses ou comunidades de sofware de código aberto, COMO É EXATAMENTE O CASO!

> Vide :
https://www.safra.com.br/pessoa-juridica/cash-management-servicos/layout-de-arquivos.htm  

> Isto posto e esclarecido, peço que os senhores reconsiderem posicionamento anterior, e

>aproveitamos para estender convite para participação no projeto a fim de melhorar a experiência de correntistas do Banco SAFRA com necessidades nas integrações de sistemas ERP com os sistemas de pagamento do banco através de contribuições diretas de vossa equipe de TI, prática muito comum de diversas empresas no mercado.

> Atenciosamente, 

> Olavo Rocha Neto

Agora, caso resolvam forçar a barra, não vejo outra alternativa senão deixar o Banco SAFRA sem integração com o BoletoNet, quem vão perder são os usuários deste banco...

**Comment by carloscds** [comment]
@olavorn Ridiculo isto, pois a informacao do layout é publica. A propósito, sua resposta foi excelente!

**Comment by olavorn** [comment]
Bom, como não perturbaram mais e nem responderam (eu teria vergonha de responder), então estou fechando essa issue.
