### ISSUE TITLE
Nuget e Wiki

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/BoletoNetCore#47]
@carloscds 
No nuget as classes Cedente e Sacado ainda existem ao invés de beneficiário e pagador, ao contrário do que está na Wiki.

Outra coisa, não existe CodMovimentoRetorno e nem CodOcorrencia, mas sim CodigoOcorrencia no boleto, assim como no boleto2Net.

Para ser sincero, não mudei uma linha do boleto2net para o boletonetcore para compilar (ainda não consegui testar).

Seria possível atualizar o nuget, por favor?

Outra coisa, este projeto está funcional? alguem usa em produção?

**Comment by carloscds** [comment]
@marcosgerene Pode atualizar e mandar um PR, o projeto foi parcialmente migrado e nao tenho informacoes de uso em produção.

**Comment by marcosgerene** [comment]
@carloscds 
Na verdade não tem o que eu atualizar ainda rs...

O que está na wiki e no código está diferente do Nuget, acredito que a primeira coisa que tem que ser feita é atualizar o nuget.

**Comment by marcosgerene** [comment]
@carloscds 
Outra coisa, o BoletoNetCore.Pdf precisava de algum tipo de licença, então optei por usar o HtmlToPDFCore que você fez.

Pretendo montar o PDf assim:
```
string html = boletoBancario.MontaHtmlEmbedded(false, true);
var pdf = new HtmlToPDFCore.HtmlToPDF().ReturnPDF(html);
```

Está ok isso? PS: estou referenciando as duas bibliotecas para .net standard.

**Comment by carloscds** [comment]
@marcosgerene Isto mesmo!

**Comment by marcosgerene** [comment]
@carloscds  meu software é construído em wpf.
Ao adicionar o HtmlToPDFCore ao nuget ele faz MUITAS referencias ao aspnetcore enorme.

Existe outra alteranativa?

**Comment by carloscds** [comment]
@marcosgerene Sobre os pacotes não tem jeito, precisa deles. Você pode criar um serviço web que faca o processo, mas só muda os pacotes de lugar.
O meu projeto nao trem muitas referencias: https://github.com/carloscds/HtmlToPDFCore/blob/master/HtmlToPDFCore/HtmlToPDFCore.csproj

**Comment by marcosgerene** [comment]
@carloscds 

Resolvi usar o html mesmo, mas existe um problema com tamanho quando vai imprimir causado pelo w150 do MENSAGEMFIXATOPOBOLETO.

![image](https://user-images.githubusercontent.com/15945003/76223775-44127500-61fa-11ea-8af9-70a629a1c76e.png)

Mesmo sem valor, como ele tem um width fixo de 150px "empurra" a linha digitavel quebrando em 2 linhas.

**Comment by rafaelpadovezi** [comment]
@carloscds Alguma razão para o nuget estar desatualizado?

**Comment by carloscds** [comment]
@rafaelpadovezi Sim, o projeto ta parado, sem ninguem contribuindo.

**Comment by rafaelpadovezi** [comment]
Para atualizar o nuget para a ultima versão 3.0.1.39, o que precisa ser feito?

**Comment by carloscds** [comment]
@rafaelpadovezi Feito!

**Comment by rafaelpadovezi** [comment]
@carloscds muito obrigado!

**Comment by marcosgerene** [comment]
@carloscds 
>Sim, o projeto ta parado, sem ninguem contribuindo.

Usar o boleto2net em .Net Standard (sem o pdf, gerando o html apenas) é possível? Ou existem mais pendências alem do PDF?

Qual o real motivo para existência deste projeto? Pelo que li e vi foi criado para não "quebrar a compatibilidade"... mas neste caso não bastaria usar um multi-target? Ex: .Net 452 e .net std 2.0 ?

**Comment by carloscds** [comment]
@marcosgerene O projeto nao esta completo, mas você pode utilizá-lo e contruibir! O PDF esta separado por opção das pessoas que começaram a migração. A ideia do projeto é criar o BoletoNET para Core, pois as duas outras versões não funcionam neste ambiente, pois tem muitas dependencias com System.Web

**Comment by marcosgerene** [comment]
@carloscds 
Quanto a usar e contribuir, assim que meu novo projeto (em .net Core) estiver "ativo", obviamente vamos contribuir o máximo possível, afinal, será uma parte vital para o funcionamento do mesmo.

A minha duvida era o "motivo" desse novo projeto ao invés de simplesmente "multi-targetiar" o boleto2Net.

Mas você já respondeu a questão sobre o System.Web.

Obrigado, abraço
