### ISSUE TITLE
Tempo de Retorno e processamento Online

### ISSUE THREAD

**Issue by olavorn** [BoletoNet/BoletoNetCore#5]
Senhores, quanto tempo em média leva para processamento do retorno do arquivo CNAB240?

Me lembro que na CEF demorava de 15 min a 2h, mas recentemente vi um caso no BB que leva um dia para processar o retorno. 

Afinal, como operacionalizar uma cobrança online com esse tempo tão longo? Vocês conhecem/trabalham com Web Services para processamento online?

**Comment by carloscds** [comment]
@olavorn Depende muito do banco. Normalmente no dia seguinte.

**Comment by olavorn** [comment]
No caso, como fazer pra gerar um boleto registrado para um comércio eletrônico, por exemplo?

**Comment by carloscds** [comment]
@olavorn alguns bancos afirmam processar o registro em alguns minutos. Mas acredito que isto se resolva quando os bancos finalizarem as APIs de integração.
