### ISSUE TITLE
Gerar Carnê

### ISSUE THREAD

**Issue by joycecouraca** [BoletoNet/BoletoNetCore#52]
Estou tentando gerar o carnê mas está dando esse erro, quando ele tenta pegar a stream BoletoNetCore.BoletoImpressao.Parts.Carne  
ERROR: {"Value cannot be null. (Parameter 'stream')"}
Como corrigir alguma luz ? 

![image](https://user-images.githubusercontent.com/38927968/88925716-4cbc2400-d24b-11ea-9da1-0028cdbded0c.png)
![image](https://user-images.githubusercontent.com/38927968/88925751-5a71a980-d24b-11ea-82be-e3c3b21df10f.png)
![image](https://user-images.githubusercontent.com/38927968/88925800-6a898900-d24b-11ea-8392-0376f2e4de41.png)

**Comment by joycecouraca** [comment]
@carloscds pode me ajudar ?

**Comment by carloscds** [comment]
@joycecouraca Qual o erro ?

**Comment by joycecouraca** [comment]
Estou tentando gerar um boleto tipo carne, só que esta apresentando problema na hora de pegar a stream 
o erro é ERROR: {"Value cannot be null. (Parameter 'stream')"}
![image](https://user-images.githubusercontent.com/38927968/88930205-86902900-d251-11ea-97e0-e814139aa306.png)

**Comment by carloscds** [comment]
@joycecouraca Ta faltanfo um ".html" no final do resource:
"BoletoNetCore.BoletoImpressao.Parts.Carne.html"

**Comment by joycecouraca** [comment]
@carloscds  Muito obrigada :), aproveitando me tirar uma duvida sobre a geração do html tem como colocar alguma margem ?

**Comment by carloscds** [comment]
@joycecouraca A margem normalmente é configurada na impressora.

**Comment by jlfjunior** [comment]
@joycecouraca Você poderia me da uma ajudinha em como gerar o modelo carnê ?
