### ISSUE TITLE
Could not load file or assembly Wkhtmltopdf.NetCore

### ISSUE THREAD

**Issue by jlfjunior** [BoletoNet/BoletoNetCore#57]
Ao utilizar o função MontaBytesPDF(), recebo esse error.

Sistema operacional utilizado Windows.

**Comment by carloscds** [comment]
@jlfjunior Você tem uma pasta chamada Rotativa junto com os binários do seu projeto ?

**Comment by jlfjunior** [comment]
@carloscds Não.

**Comment by carloscds** [comment]
@jlfjunior 
https://github.com/fpanaccia/Wkhtmltopdf.NetCore

Se preferir use este outro pacote: https://www.nuget.org/packages/HtmlToPDFCore/

**Comment by jlfjunior** [comment]
@carloscds Após mover a pasta rotativa para o bin e adicioanar a primeira biblioteca mencionada acontece o erro a baixo.

An exception of type 'System.TypeLoadException' occurred in BankSlip.Api.dll but was not handled in user code: 'Could not load type 'Wkhtmltopdf.NetCore.HtmlAsPdf' from assembly 'Wkhtmltopdf.NetCore, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null'.'

**Comment by carloscds** [comment]
@jlfjunior Ja deu uma olhada no Git do componente?

**Comment by jlfjunior** [comment]
@carloscds Já sim, não encontrei nada relacionado. Eu sou iniciante em desenvolvimento, pelo que entendi falta da load nos arquivos qu já são encontrados no diretorio Rotativa, você se recorda de mais alguma configuração necessária ?

**Comment by carloscds** [comment]
@jlfjunior eu nao uso este componente, por isto fiz um outro que ja inclui tudo que é necessário. Tenta utilizar esta: https://www.nuget.org/packages/HtmlToPDFCore/

**Comment by jlfjunior** [comment]
@carloscds sendo assim a função MontaBytes() está depreciada,

Eu contornei a situação da seguinte manteria.

* Instalei Wkhtmltopdf.NetCore versão 3.0.2.
* Adicionei a pasta Rotativa ao diretorio do projeto e fiz a configuração para mover os arquivoss para pasta bin.
* Fiz o uso da função GetPDF() passando o conteudo gerado através da função MontaHtmlEmbedded().


Será que não seria interessante atualizar o projeto pa versão mas recente já que a função MontaBytes faz uso dessa biblioteca ?

**Comment by carloscds** [comment]
@jlfjunior Gostaria de enviar um Pull Requesst com a correcao ?

**Comment by jlfjunior** [comment]
@carloscds Seria uma honra, gostaria também de criar um **Readme** ensinando como usar só a parte de impressão de boletos.

**Comment by carloscds** [comment]
@jlfjunior Excelente, so mandar entao.

**Comment by olavorn** [comment]
A visão inicial desta forma era separar o BoletoNet.Core do BoletoNet.Pdf, assim se você quiser usar o Pdf, tem que ter as duas bibliotecas instaladas. Creio que o pacote BoletoNetCore.Pdf do nuget precisa ajustar a referência para embarcar estes binários. Por isso no meu fork eu uso os projetos ainda sem o nuget, mas uso o PDF. Isso ocorre pq para fins de deploy em máquinas docker, utilizo um script para instalar essas bilbliotecas no SO (e não no projeto), pois rodam em linux.

**Comment by carloscds** [comment]
@olavorn Na verdade o deploy precisa ser ajudado ao ambiente onde vai rodar, mas o projeto atual nao inclui nem referencia os arquivos Rotativa.

**Comment by olavorn** [comment]
Sim, inclui.

https://github.com/BoletoNet/BoletoNetCore/tree/master/BoletoNetCore.Pdf/Rotativa

**Comment by carloscds** [comment]
@olavorn Viu a mensagem acima ?

**Comment by olavorn** [comment]
@carloscds eu vi, mas não acho que o problema seja a referência em si. Acredito que há alguma limitação no empacotamento que aplica um strip nos arquivos no momento em que eles são publicados no nuget.

**Comment by jlfjunior** [comment]
@carloscds @olavorn Adicionei a biblioteca https://www.nuget.org/packages/HtmlToPDFCore/ para gerar o conteudo pdf.
