### ISSUE TITLE
Inclusão dos Motivos e Ocorrências do CNAB240

### ISSUE THREAD

**Issue by olavorn** [BoletoNet/BoletoNetCore#6]
Pessoal, já iniciando um processo mais imersivo de revisão do nosso projeto, verifiquei uma coisa em função do Uso:

O que a gente denomina como Ocorrência na verdade aponta para C044 (Código de Movimento Retorno), de fato não está correspondente ao que o manual do CNAB aponta em sua versão mais atual. 

Para não exigir breaking changes no futuro mais traumáticos, como o próprio @rafd75 posicionou algumas vezes, eu sugiro que a gente implemente um mutirão de verificação do correto mapeamento dos campos da classe Boleto em relação ao CNAB240. 

Também acho que seria uma boa incluirmos em cada campo a referência da descrição do manual. Ex. C044. 

O que vcs acham? Posso iniciar um PR com este fim e se for o caso, ajustar os testes que eventualmente estiverem incorretos (embora acredite que só passe de refactoring mesmo)

**Comment by rafd75** [comment]
@olavorn , bom dia.

Como foi iniciado um novo projeto (BoletoNetCore), acredito que seja a hora oportuna desse tipo de revisão. Foi o que eu fiz com o Boleto2Net, quando publiquei a primeira vez.

Veja se entendi: Boleto.Ocorrencia seria renomeado para Boleto.CodMovimentoRetorno (ou algo assim)? 

Considerando incluir a referência do manual, seria algo do tipo Boleto.CodMovimentoRetorno_C044 - mais ou menos isso? .... Se for isso, incluir esse C044, eu não sei se seria uma boa. O CNAB240 tem um padrão bem definido, mas já peguei algumas particularidades entre um banco e outro (só não me recordo agora qual banco, qual particularidade). Neste caso, pode complicar a longo prazo. E se entendermos que o CNAB400 acaba sendo implementado junto, não sei se na prática funcionaria... (Talvez, em forma de anotação, comentário, algo assim, poderia ser uma boa ideia).

Quanto ao multirão, infelizmente eu não estou com agenda disponível para isso, então prefiro nesse momento não me comprometer... mas o projeto me interessa... e pretendo em breve utilizar esse no lugar do Boleto2Net.

**Comment by olavorn** [comment]
> Considerando incluir a referência do manual, seria algo do tipo Boleto.CodMovimentoRetorno_C044 - mais ou menos isso? .... Se for isso, incluir esse C044, eu não sei se seria uma boa.

Não não, pensei em incluir como comentário nas propriedades correspondentes na classe boleto mesmo, ou até mesmo como uma classe Atributo para ajudas a rastrear se necessitar, mas acho que apenas como comentário é mais do que suficiente.

**Comment by olavorn** [comment]
Por serem comentários, creio que não necessite ser algo que tem que ser fechado e entregue em uma data específica, pois todos nós realmente temos outras atividades tb para tocar. Pra alinhar, acho suficiente e viável perseguir isso fazendo aos poucos, no sentido de incluir como práticas e ir promovendo essas alterações ao longo do tempo mesmo. Mesmo que não seja de todos os campos, mas pelo menos da lista de campos de controle que já utilizamos hoje seria importante. 

Para os campos que tinham um significado e mudaram, poderíamos até incluir algum atributo de warning para alertar os usuários que eventualmente forem sofrer com essa diferença.

**Comment by rafd75** [comment]
Ai sim... Ajudaria muito.

Vi que vc já alterou os namespaces (Boleto2Net para BoletoNetCore) então quanto ao nome das propriedades, se for necessário alterar (ex: Ocorrencia para CodigoMovimentoRetorno), eu acredito que seja a hora ideal...

**Comment by olavorn** [comment]
Dá uma olhada nesse commit. Resume o que conversamos e já introduz um modelo.

https://github.com/ExodusSistemas/BoletoNetCore/commit/19fd98f512aec952d16b68f2870ca6877a7334af
