### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by michael-nel** [BoletoNet/BoletoNetCore#66]
Olá gostaria de saber quanto em quanto tempo é gerado uma nova release. Acabei de subir uma implementação que preciso dela.

**Comment by jlfjunior** [comment]
Tenho essa mesma duvida @michael-nel. Abrir um PR relativamente simples.

https://github.com/BoletoNet/BoletoNetCore/pull/64

Estou precisando muito disso.

**Comment by carloscds** [comment]
@jlfjunior @michael-nel Peço desculpas mas estou muito corrido nas ultimas semanas, mas vou gerar uma nova release. Este projeto não tem um pipeline integrado que facita isto.

**Comment by jlfjunior** [comment]
@carloscds Obrigado.

Estou conhecendo em breve quero contribuir mais para o projeto.

**Comment by carloscds** [comment]
@jlfjunior  @michael-nel Pacote atualizado, agora ta automatizado!

**Comment by michael-nel** [comment]
@carloscds O Pacote não esta automatizado? Ontém fiz uma PR de uma carteira e até o momento não subiu a nova versão.

**Comment by carloscds** [comment]
@michael-nel Nao, somente do myget. Para nuget eu gero. Isto é para seguranca! Se você quer pegar o pacote logo apos o build, so apontar para o feed do myget.

**Comment by michael-nel** [comment]
@carloscds Carlos poderia gerar uma nova release por favor? facilita minha vida no deploy hehe

**Comment by michael-nel** [comment]
@carloscds poderia gerar a nova release no nuget? Na ultima PR implementei a carteira 05 e estou precisando dessa implementação.

**Comment by carloscds** [comment]
@michael-nel Ultimo build no Myget tem 10 dias, é este mesmo?

**Comment by michael-nel** [comment]
@carloscds Isso mesmo, nesse build implementei a carteira 05.

**Comment by carloscds** [comment]
@michael-nel feito!

**Comment by michael-nel** [comment]
@carloscds poderia gerar a release com essa nova carteira do itaa por favor? Vou adicionar no meu repositório privado do projeto o MyGet, por hora esta o Nugget para processo de CD/CI.

**Comment by carloscds** [comment]
@michael-nel Enviando para nuget.

**Comment by michael-nel** [comment]
@carloscds poderia gerar a release por favor ? criei o cnab240 do banco Nordeste. Vou homologar na aplicação e futuramente desenvolvo o boleto do banco nordeste.

**Comment by carloscds** [comment]
@michael-nel publicando.
