### ISSUE TITLE
Campo Codigo do (antigo) Cedente

### ISSUE THREAD

**Issue by leandrokoiti** [BoletoNet/BoletoNetCore#72]
Fala pessoal, estou em um projeto migrando um código do BoletoNet para o BoletoNetCore, percebi que ele é um "port" do Boleto2.Net e no geral estou conseguindo entender as mudanças com base nos readme e o de migração, porém me surgiu uma dúvida: A remoção do campo Codigo da classe Beneficiario foi proposital?

Vi que no Boleto2.Net na classe Cedente ainda existe o campo, mas no Beneficiario não achei um equivalente e fiquei com dúvida sobre quem seria o equivalente nele.

Obrigado!

**Comment by carloscds** [comment]
@leandrokoiti A ideia é simplificar o código. Nãoi ha um motivo específico sobre remover o campo.

**Comment by leandrokoiti** [comment]
Entendi, obrigado @carloscds , daí nesse caso ele não precisa ser utilizado então? Ou é possível alcançar o mesmo efeito de outra forma agora?

**Comment by carloscds** [comment]
@leandrokoiti nao precisa.
