### ISSUE TITLE
Validação de banco e carteira homologado

### ISSUE THREAD

**Issue by thiagokernell** [BoletoNet/BoletoNetCore#75]
Prezados, existe algum método para validar se a carteira ou o banco estão homologados? Ou algum método que traga uma lista com os bancos/carteira homologados?

Digo isso, pois em meu sistema quero exibir apenas os bancos/carteiras homologados e precisava desse método para carregar, é possível?

**Comment by carloscds** [comment]
@thiagokernell Esta informacao existe apenas na documentacao do projeto.

**Comment by thiagokernell** [comment]
Ok, Obrigado

**Comment by thiagokernell** [comment]
Seria interessante, ter esses métodos para auxiliar na exibição para o nosso usuário do que tem homologado, do que depender da documentação. Digo isso, pois ficaria uma informação mais confiavel vinda direta do fonte.
