### ISSUE TITLE
Dúvida nosso número

### ISSUE THREAD

**Issue by thiagokernell** [BoletoNet/BoletoNetCore#76]
O nosso número ele deve ser único por carteira, ou a numeração dele é independente da carteira?
Exemplo:

Bradesco, Carteira 09, nosso numero 1
Bradesco, Carteira 09, nosso numero 2

Bradesco, Carteira 04, nosso numero 1
Bradesco, Carteira 04, nosso numero 2

OU 

Bradesco, Carteira 09, nosso numero 1
Bradesco, Carteira 09, nosso numero 2

Bradesco, Carteira 04, nosso numero 3
Bradesco, Carteira 04, nosso numero 4

Qual númeração aplicar?

**Comment by carloscds** [comment]
@thiagokernell Normalmente é por carteira, mas aconselho validar com o banco.

**Comment by thiagokernell** [comment]
Como estou implementando o boleto.net para teoricamente emitir para qualquer banco no meu ERP, então acho mais garantido deixar por padrão a númeração independente da carteira, pois isso garante númeração única e não teria problema com conflitos.
