### ISSUE TITLE
Problema arquivo remessa banco Bradesco CNAB240 Carteira 09

### ISSUE THREAD

**Issue by gsysteminformaticarp** [BoletoNet/BoletoNetCore#77]
Olá não sei se alguém já homologou o Banco Bradesco CNAB240 Carteira 09, pois estou tendo problemas na primeira homologação com o banco e notei que realmente esta sendo preenchido incorretamente as posições que o banco retornou com o erro

 já analisei o que precisa ser ajustado posso realizar os ajustes e enviar um PR?

Retorno banco
Linha 1, colunas 072 a 072, Header de arquivo, Dígito verificador. Deixar em branco.
Linha 1, colunas 167 a 171, Header de arquivo, densidade de gravação do arquivo inválida. 01600 ou 06250.
Linha 2, colunas 073 a 073, Header de lote, dígito verificador. Deixar em branco.
Linha 3, colunas 018 a 023, número da agência/dígito não numérico
Linha 3, colunas 037 a 037, dígito verificador. Deixar em branco.
Linha 5, colunas 200 a 207, Cód. Ocorr. do Pagador não numérico. (Não tratado pelo banco).
Linha 5, colunas 231 a 231, Aviso para débito automático não informado ou inválido.
Linha 7, colunas 018 a 023, número da agência/dígito não numérico
Linha 7, colunas 037 a 037, dígito verificador. Deixar em branco.

**Comment by carloscds** [comment]
@gsysteminformaticarp Da uma olhada no historico de mudanças e compara tambem com o boletoNet original.

**Comment by gsysteminformaticarp** [comment]
@carloscds Fiz exatamente isso mesmo, olhei histórico de mudanças e comparei com boletoNet,  comparando com boletoNet foi onde notei que no boletoNet esta gerando corretamente as linhas que deu problema no processo de homologação, então vou realizar esses ajustes no boletoNetCore

**Comment by carloscds** [comment]
@gsysteminformaticarp Excelente, mandeu um PR por favor.

**Comment by gsysteminformaticarp** [comment]
Olá @carloscds Realizei os ajustes, e analisei a remessa gerada esta de acordo com os ajustes solicitado pelo banco. Ficou pendente somente enviar uma remessa nova para o banco com os ajustes realizados e aguardar o retorno do banco. pois o Bradesco não possui validador online para CNAB240.

**Comment by carloscds** [comment]
@gsysteminformaticarp Excelente, so mandar o PR. Obrigado!!!

**Comment by gsysteminformaticarp** [comment]
@carloscds obrigado vou aguardar o retorno do banco e comento aqui se passou com sucesso na homologação para encerrarmos essa Iss

**Comment by gsysteminformaticarp** [comment]
@carloscds Remessa aprovada pelo banco.

**Comment by mateusdev25** [comment]
estou com esse mesmo problema e não sei como resolver, @gsysteminformaticarp  voce conseguiria me dar uma ajuda ?

**Comment by mateusdev25** [comment]
@carloscds poderia me ajudar com isso pfv ?

**Comment by carloscds** [comment]
@mateusdev25 Qual o problema, vc preencheu todos os objetos ? tem alguma mensagem de erro ?

**Comment by mateusdev25** [comment]
@carloscds  então, o arquivo de remessa ta dando esse mesmo erro

**Comment by marcianobandeira** [comment]
boa tarde pessoal, tenho clientes utilizando a carteira 09 do bradesco diariamente, nao tenho tido relato de problemas

**Comment by mateusdev25** [comment]
pq so comigo isso aconteceu kkkkkk

**Comment by mateusdev25** [comment]
e o pior é que não sei como resolver

**Comment by marcianobandeira** [comment]
neste caso seria melhor abrir um topico la, ou trocar para o BoletoNetCore hehe

**Comment by mateusdev25** [comment]
eu to pensando em trocar pro boletonetcore realmente

**Comment by mateusdev25** [comment]
vou tentar trocar, se eu nao conseguir voces conseguem me dar um help ?

**Comment by marcianobandeira** [comment]
opa, no que estiver ao alcance, estamos ai

**Comment by carloscds** [comment]
@mateusdev25 o boleto2net é com o Rodolfo, eu nao trabalho diretamente neste código.

**Comment by mateusdev25** [comment]
@carloscds, @marcianobandeira algum de voces tem discord ?

**Comment by mateusdev25** [comment]
não consegui implementar o boletonetcore no meu sistema, sera que dava pra voces me dar uma ajuda, eu dou um agrado

**Comment by carloscds** [comment]
@mateusdev25 Você olhou o projeto de testes do boletonet ? Da para usá-lo como referencia.
