### ISSUE TITLE
Código de Barra não pode ser atribuído?

### ISSUE THREAD

**Issue by RiccardoCafa** [BoletoNet/BoletoNetCore#85]
Salve pessoal do boleto net core, primeiramente parabéns pelo projeto e iniciativa.

Uma dúvida que me surgiu e talvez não tenha ficado claro no README do repositório, o BoletoNetCore gera apenas o documento do boleto ou também emite de fato o boleto no banco? Pois, pelo que eu tinha entendido ele só emitia o documento, no caso, em Html, mas sem código de barras nem linha digitavel. 

Então fui no Banco do Brasil e fiz uma integração com a API deles para gerar esses valores cruciais para o funcionamento do boleto, mas aparentemente quando tento instanciar um código de barras no meu objeto Boleto diz que não pode ser atribuído.

Poderiam me tirar essa dúvida?

Agradeço desde já.

**Comment by carloscds** [comment]
@RiccardoCafa O BoletoNet gera o boleto, e pode registrar no banco usando um arquivo de remessa. Quanto a instanciar o codigo de barras nao ficou claro qual o erro, poderia explicar ?

**Comment by RiccardoCafa** [comment]
Agora entendi o arquivo de remessa... desculpe, então seria o CNAB certo? Andei pesquisando algumas documentações e achei essa informação por agora.

De toda forma, a API do banco do Brasil já está integrada e como me pediram pra implementar o PIX também, seria legal já usar o que o Banco do Brasil me oferece. Já consigo gerar o boleto e obter o código de barras e a linha digitavel. Entretanto, não consigo acessar a propriedade **CodigoBarra**, teria como setar isso ou tem alguma outra forma?

```cs
Boleto boletoNet = new Boleto(Banco.Instancia(Bancos.BancoDoBrasil));

boletoNet.CodigoBarra = new CodigoBarra() // Erro, pois "codigo barra" só tem get publico.
{ 
    CodigoDeBarras = "codigo de barras gerado pelo banco do brasil",
    LinhaDigitavel = "linha digitavel gerado pelo banco do brasil"
};
```

Uma vez que eu consiga fazer funcionar, posso me disponibilizar para fazer um "**Getting Started**" para o _BoletoNetCore_ para ajudar pessoas que estão chegando por agora.

Agradeço a atenção.
