### ISSUE TITLE
[Safra - CNAB 400] - Inconsistência

### ISSUE THREAD

**Issue by MatheusVCoelho97** [BoletoNet/BoletoNetCore#86]
Boa tarde,

No banco Safra, CNAB 400, estou recebendo este retorno:

![image](https://user-images.githubusercontent.com/61600216/107415208-d6e61e80-6af1-11eb-900b-3e0212903880.png)

Olhando o código, notei que essa informação é controlada pelo atributo "NumeroArquivoRemessaCNAB400", mas não consegui encontrar nenhum momento em que o valor é atribuído.

Existe algo que eu possa fazer ou é algo relacionada ao BoletoNetCore?

Obrigado

**Comment by marcosgerene** [comment]
Fiz uma pequena alteração, basicamente atribui o valor da variável ao gerar o Header, por favor faça o teste.

https://github.com/BoletoNet/BoletoNetCore/pull/87

PS: a alteração não gerou erros nos testes automatizados

![image](https://user-images.githubusercontent.com/15945003/107417088-fed68180-6af3-11eb-9f6e-eca285a51d53.png)

**Comment by marcosgerene** [comment]
@MatheusVCoelho97

A correção foi aceita, atualize o nuget quando o @carloscds liberar a nova versão.

**Comment by carloscds** [comment]
@marcosgerene Vou gerar um novo pacote

**Comment by MatheusVCoelho97** [comment]
Alterei manualmente o arquivo de remessa só modificando as informações corretas e as remessas foram validadas. Atualizei o nuget, testei novamente e está funcionando corretamente. Muito obrigado, abraços!
