### ISSUE TITLE
Classe "BancoFebraban" ?

### ISSUE THREAD

**Issue by olavorn** [BoletoNet/BoletoNetCore#9]
Para reunir um pouco do código repetido em várias das classes Banco, senti falta de uma classe ancestral das classes BancoBradesco, BancoBrasil etc..

Ia propor uma classe abstrata BancoFebraban que não necessariamente implementasse IBanco, mas que contivesse um punhado de implementações que fossem comuns a todos. O que vcs acham?

**Comment by carloscds** [comment]
@olavorn Isto pode complicar um pouco o projeto. Entendio que existe código repetido, mas tudo esta dentro da classe de cada banco. Se começar a dividir isto, uma mudança nesta classe Ancestral pode quebrar o codigo de tudo, e não somente do banco em questão. 
my 2 cents.

**Comment by olavorn** [comment]
Hum, ok. 

Eu pensei na possibilidade também de fazer por um Helper, mas como boa parte da lógica está em métodos internos private, ficaria inviável... 

O trade-off é que todas as funcionalidades ou arranjos a partir do padrão CNAB terão que ser refletidos em todos os Bancos tb. :/ 

Vou fazer o commit em uma branch apenas com a idéia e 2 bancos que eu uso implementados dessa forma, apenas pra avaliar. Ambos dividindo alguns métodos, como o LerRetornoSegmentoXX e alguns outros que vi 100 igual..

**Comment by olavorn** [comment]
https://github.com/ExodusSistemas/BoletoNetCore/tree/bancofebraban

**Comment by carloscds** [comment]
@olavorn ok.
