### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by michael-nel** [BoletoNet/BoletoNetCore#98]
@carloscds enviei a PR, porém olhei no https://www.myget.org/gallery/boletonetcorebuild e a última versão é de 15 dias atrás. Poderia gerar uma nova release ? Preciso implementar no projeto código que enviei ontém.

**Comment by carloscds** [comment]
@michael-nel Vou gerar, mas nao posso gerar uma versao a cada PR ok, para versões mais novas, você pode usar o Myget: https://www.myget.org/gallery/boletonetcorebuild

**Comment by michael-nel** [comment]
@carloscds entendo, por isso olhei no myget antes e como não foi gerado o novo build, fiz a solicitação.

**Comment by carloscds** [comment]
@michael-nel Todo PR gera um build no MyGet.

**Comment by michael-nel** [comment]
@carloscds acho que houve algum problema, pois não gerou build desse PR, tanto que voce gerou a release no nugget do ultimo build 3.0.1.101 de 15 dias atrás.

**Comment by carloscds** [comment]
@michael-nel Me parece que quebrou algo no build deste PR: https://ci.appveyor.com/project/carloscds/boletonetcore/builds/38002808

**Comment by michael-nel** [comment]
@carloscds ele passou nos testes e deu build com sucesso. Estranho não ?

**Comment by carloscds** [comment]
@michael-nel sim, vou verificar.

**Comment by carloscds** [comment]
@michael-nel Resolvido
